import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import net.sourceforge.plantuml.activitydiagram3.ftile.ArrowsRegular;
import net.sourceforge.plantuml.activitydiagram3.ftile.FtileGeometry;
import net.sourceforge.plantuml.activitydiagram3.ftile.MergeStrategy;
import net.sourceforge.plantuml.activitydiagram3.ftile.Worm;
import net.sourceforge.plantuml.activitydiagram3.ftile.WormMutation;
import net.sourceforge.plantuml.klimt.UTranslate;
import net.sourceforge.plantuml.klimt.geom.XPoint2D;

/**
 * Dumps the arithmetic of activity arrows and tile geometry on generated inputs, for the exact replay test in
 * crates/rockuml/src/ftile/tests/arrows.rs: worms merged after being moved (Worm.merge with its straightening rules),
 * the offsets of multi-colour arrows (WormMutation), and chains of FtileGeometry operations. Doubles are written as
 * their 16 hex digit IEEE bits.
 */
public class ArrowDump {
	private final Random random = new Random(20261008);
	private final PrintStream out;

	private ArrowDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new ArrowDump(out).run();
		}
	}

	private void run() {
		out.println("# Generated by tools/oracle/activity-unit/arrows.sh from ArrowDump.java; do not edit.");
		for (int i = 0; i < 400; i++)
			merge();
		for (int i = 0; i < 300; i++)
			mutation();
		for (int i = 0; i < 300; i++)
			geometry();
	}

	private static String hex(double value) {
		return String.format("%016x", Double.doubleToRawLongBits(value));
	}

	private String points(Worm worm) {
		final StringBuilder result = new StringBuilder();
		for (int i = 0; i < worm.size(); i++) {
			final XPoint2D point = worm.getPoint(i);
			result.append(' ').append(hex(point.getX())).append(',').append(hex(point.getY()));
		}
		return result.toString();
	}

	private double coordinate() {
		return random.nextInt(4) == 0 ? random.nextInt(2000) / 10.0 : random.nextInt(200);
	}

	private double length() {
		return random.nextInt(4) == 0 ? 1 + random.nextInt(400) / 10.0 : 1 + random.nextInt(40);
	}

	/** Mostly down, as arrows of activity diagrams go. */
	private List<XPoint2D> path(XPoint2D start, int segments) {
		final List<XPoint2D> result = new ArrayList<>();
		result.add(start);
		XPoint2D current = start;
		for (int i = 0; i < segments; i++) {
			final int direction = random.nextInt(10);
			final double length = length();
			if (direction < 4)
				current = new XPoint2D(current.getX(), current.getY() + length);
			else if (direction < 6)
				current = new XPoint2D(current.getX() - length, current.getY());
			else if (direction < 8)
				current = new XPoint2D(current.getX() + length, current.getY());
			else
				current = new XPoint2D(current.getX(), current.getY() - length);
			result.add(current);
		}
		return result;
	}

	private static Worm worm(List<XPoint2D> points) {
		final Worm result = new Worm(null, new ArrowsRegular());
		for (XPoint2D point : points)
			result.addPoint(point);
		return result;
	}

	private String coordinates(List<XPoint2D> points) {
		final StringBuilder result = new StringBuilder();
		for (XPoint2D point : points)
			result.append(' ').append(hex(point.getX())).append(',').append(hex(point.getY()));
		return result.toString();
	}

	/** Two worms joined end to start, moved by the same amount, merged, moved back, as UGraphicForSnake does. */
	private void merge() {
		final List<XPoint2D> first = path(new XPoint2D(coordinate(), coordinate()), 1 + random.nextInt(4));
		final List<XPoint2D> second = path(first.get(first.size() - 1), 1 + random.nextInt(4));
		final MergeStrategy strategy = random.nextBoolean() ? MergeStrategy.FULL : MergeStrategy.LIMITED;
		final double dx = random.nextInt(1000) / 10.0 - 50;
		final double dy = random.nextInt(1000) / 10.0 - 50;
		out.println("merge " + strategy + " " + hex(dx) + " " + hex(dy));
		out.println("a" + coordinates(first));
		out.println("b" + coordinates(second));
		final Worm moved1 = worm(first).move(dx, dy);
		final Worm moved2 = worm(second).move(dx, dy);
		out.println("r" + points(moved1.merge(moved2, strategy).move(-dx, -dy)));
	}

	private void mutation() {
		final List<XPoint2D> points = path(new XPoint2D(coordinate(), coordinate()), 1 + random.nextInt(3));
		final double delta = 2 + random.nextInt(4);
		final int colors = 2 + random.nextInt(3);
		out.println("mutation " + hex(delta) + " " + colors);
		out.println("w" + coordinates(points));
		final Worm worm = worm(points);
		try {
			final WormMutation mutation = WormMutation.create(worm, delta);
			final UTranslate first = mutation.getFirst();
			final UTranslate last = mutation.getLast();
			final UTranslate text = mutation.getTextTranslate(colors);
			out.println("m " + mutation.size() + " " + hex(first.getDx()) + "," + hex(first.getDy()) + " "
					+ hex(last.getDx()) + "," + hex(last.getDy()) + " " + hex(text.getDx()) + " "
					+ mutation.isDxNegative());
			out.println("p" + points(mutation.mute(worm)));
		} catch (RuntimeException e) {
			out.println("fails");
		}
	}

	private double amount() {
		return random.nextInt(3) == 0 ? random.nextInt(1000) / 10.0 : random.nextInt(50);
	}

	private FtileGeometry randomGeometry() {
		final double width = amount();
		final double height = amount();
		final double left = amount();
		final double inY = amount();
		if (random.nextBoolean())
			return new FtileGeometry(width, height, left, inY);
		return new FtileGeometry(width, height, left, inY, amount());
	}

	private String describe(FtileGeometry geometry) {
		return hex(geometry.getWidth()) + " " + hex(geometry.getHeight()) + " " + hex(geometry.getLeft()) + " "
				+ hex(geometry.getInY()) + " " + hex(geometry.getOutY()) + " " + geometry.hasPointOut();
	}

	/** A start, then operations each printed with its arguments and the geometry after it. */
	private void geometry() {
		FtileGeometry geometry = randomGeometry();
		out.println("geometry " + describe(geometry));
		for (int i = 0; i < 6; i++) {
			final double a = amount();
			final double b = amount();
			final int op = random.nextInt(12);
			final String args;
			switch (op) {
			case 0:
				geometry = geometry.incHeight(a);
				args = "incHeight " + hex(a);
				break;
			case 1:
				geometry = geometry.addTop(a);
				args = "addTop " + hex(a);
				break;
			case 2:
				geometry = geometry.addBottom(a);
				args = "addBottom " + hex(a);
				break;
			case 3:
				geometry = geometry.incRight(a);
				args = "incRight " + hex(a);
				break;
			case 4:
				geometry = geometry.incLeft(a);
				args = "incLeft " + hex(a);
				break;
			case 5:
				geometry = geometry.incVertically(a, b);
				args = "incVertically " + hex(a) + " " + hex(b);
				break;
			case 6:
				geometry = geometry.incInY(a);
				args = "incInY " + hex(a);
				break;
			case 7:
				geometry = geometry.withoutPointOut();
				args = "withoutPointOut";
				break;
			case 8:
				geometry = geometry.translate(new UTranslate(a, b));
				args = "translate " + hex(a) + " " + hex(b);
				break;
			case 9: {
				// Nothing added keeps a missing point out missing; anything else gives the tile one.
				final double deltaHeight = random.nextInt(4) == 0 ? 0 : b;
				geometry = geometry.addDim(a, deltaHeight);
				args = "addDim " + hex(a) + " " + hex(deltaHeight);
				break;
			}
			case 10:
				geometry = geometry.fixedHeight(a);
				args = "fixedHeight " + hex(a);
				break;
			default: {
				final FtileGeometry other = randomGeometry();
				geometry = geometry.appendBottom(other);
				args = "appendBottom " + describe(other);
			}
			}
			out.println(args);
			out.println("= " + describe(geometry));
		}
	}
}
