import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import net.sourceforge.plantuml.activitydiagram3.ftile.CenteredText;
import net.sourceforge.plantuml.klimt.UChange;
import net.sourceforge.plantuml.klimt.UPath;
import net.sourceforge.plantuml.klimt.UShape;
import net.sourceforge.plantuml.klimt.UStroke;
import net.sourceforge.plantuml.klimt.UTranslate;
import net.sourceforge.plantuml.klimt.compress.CompressionMode;
import net.sourceforge.plantuml.klimt.compress.CompressionXorYBuilder;
import net.sourceforge.plantuml.klimt.drawing.UGraphic;
import net.sourceforge.plantuml.klimt.drawing.UGraphicNo;
import net.sourceforge.plantuml.klimt.drawing.debug.StringBounderDebug;
import net.sourceforge.plantuml.klimt.font.FontConfiguration;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.font.UFontFactory;
import net.sourceforge.plantuml.klimt.geom.MinMax;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;
import net.sourceforge.plantuml.klimt.geom.XPoint2D;
import net.sourceforge.plantuml.klimt.shape.TextBlock;
import net.sourceforge.plantuml.klimt.shape.UEllipse;
import net.sourceforge.plantuml.klimt.shape.UEmpty;
import net.sourceforge.plantuml.klimt.shape.ULine;
import net.sourceforge.plantuml.klimt.shape.UPolygon;
import net.sourceforge.plantuml.klimt.shape.URectangle;
import net.sourceforge.plantuml.klimt.shape.UText;

/**
 * Compresses generated scenes of shapes across (ON_X), down (ON_Y) and both, as activity diagrams do, and dumps the
 * compressed dimension, the min-max PlantUML measures on it and every primitive the compressed drawing hands the
 * surface below, for the exact replay test in crates/rockuml/src/klimt/compress/tests.rs. A scene line lists one
 * shape: two translations applied one after the other, a stroke thickness or '-', the kind and its parameters.
 * Doubles are written as their 16 hex digit IEEE bits.
 */
public class CompressDump {
	private final Random random = new Random(20261008);
	private final PrintStream out;
	private final StringBounder stringBounder = new StringBounderDebug();

	private CompressDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new CompressDump(out).run();
		}
	}

	private void run() {
		out.println("# Generated by tools/oracle/activity-unit/compress.sh from CompressDump.java; do not edit.");
		for (int i = 0; i < 150; i++)
			scene();
	}

	private static String hex(double value) {
		return String.format("%016x", Double.doubleToRawLongBits(value));
	}

	private static String at(UTranslate translate) {
		return hex(translate.getDx()) + "," + hex(translate.getDy());
	}

	/** Mostly whole numbers, as tiles place things, sometimes tenths. */
	private double coordinate() {
		return random.nextInt(3) == 0 ? random.nextInt(4000) / 10.0 : random.nextInt(400);
	}

	/** Never zero: PlantUML fails on a shape without extent. */
	private double size() {
		return random.nextInt(3) == 0 ? 1 + random.nextInt(600) / 10.0 : 1 + random.nextInt(60);
	}

	private double offset() {
		return random.nextInt(81) - 40;
	}

	private String word() {
		final StringBuilder result = new StringBuilder();
		final int length = 1 + random.nextInt(8);
		for (int i = 0; i < length; i++)
			result.append((char) ('a' + random.nextInt(26)));
		return result.toString();
	}

	private static String mode(CompressionMode mode) {
		return mode == null ? "-" : mode.name();
	}

	/** One shape and the line describing it. */
	private static final class Shape {
		final UShape shape;
		final String description;

		Shape(UShape shape, String description) {
			this.shape = shape;
			this.description = description;
		}
	}

	/** A block of fixed size drawing a rectangle of that size, as the text of a centred title. */
	private static TextBlock block(final double width, final double height) {
		return new TextBlock() {
			public XDimension2D calculateDimension(StringBounder stringBounder) {
				return new XDimension2D(width, height);
			}

			public void drawU(UGraphic ug) {
				ug.draw(URectangle.build(width, height));
			}
		};
	}

	private Shape shape() {
		switch (random.nextInt(9)) {
		case 0:
		case 1: {
			final double width = size();
			final double height = size();
			final boolean ignoreX = random.nextInt(4) == 0;
			final boolean ignoreY = random.nextInt(4) == 0;
			URectangle rect = URectangle.build(width, height);
			if (ignoreX)
				rect = rect.ignoreForCompressionOnX();
			if (ignoreY)
				rect = rect.ignoreForCompressionOnY();
			return new Shape(rect, "rect " + hex(width) + " " + hex(height) + " " + ignoreX + " " + ignoreY);
		}
		case 2: {
			final double dx = random.nextInt(3) == 0 ? 0 : offset() * 2;
			final double dy = random.nextInt(3) == 0 ? 0 : offset() * 2;
			return new Shape(new ULine(dx, dy), "line " + hex(dx) + " " + hex(dy));
		}
		case 3: {
			final CompressionMode mode = random.nextBoolean() ? null
					: random.nextBoolean() ? CompressionMode.ON_X : CompressionMode.ON_Y;
			final UPolygon polygon = new UPolygon();
			final StringBuilder description = new StringBuilder("polygon " + mode(mode));
			final double width = size();
			final double height = size();
			final double[][] points = random.nextBoolean()
					? new double[][] { { 0, 0 }, { width, height / 2 }, { 0, height } }
					: new double[][] { { -width / 2, 0 }, { width / 2, 0 }, { 0, height } };
			for (double[] point : points) {
				polygon.addPoint(point[0], point[1]);
				description.append(' ').append(hex(point[0])).append(',').append(hex(point[1]));
			}
			polygon.setCompressionMode(mode);
			return new Shape(polygon, description.toString());
		}
		case 4: {
			final double width = size();
			final double height = size();
			return new Shape(UEllipse.build(width, height), "ellipse " + hex(width) + " " + hex(height));
		}
		case 5: {
			final int fontSize = 8 + random.nextInt(13);
			final String word = word();
			final UText text = UText.build(word, FontConfiguration.blackBlueTrue(UFontFactory.serif(fontSize)));
			return new Shape(text, "text " + fontSize + " " + word);
		}
		case 6: {
			final UPath path = UPath.none();
			final StringBuilder description = new StringBuilder("path");
			final List<XPoint2D> points = new ArrayList<>();
			points.add(new XPoint2D(0, 0));
			points.add(new XPoint2D(size(), size()));
			for (int i = random.nextInt(3); i > 0; i--)
				points.add(new XPoint2D(offset(), offset()));
			for (int i = 0; i < points.size(); i++) {
				final XPoint2D point = points.get(i);
				if (i == 0)
					path.moveTo(point);
				else
					path.lineTo(point);
				description.append(' ').append(hex(point.getX())).append(',').append(hex(point.getY()));
			}
			return new Shape(path, description.toString());
		}
		case 7: {
			final double width = size();
			final double height = size();
			return new Shape(new UEmpty(width, height), "empty " + hex(width) + " " + hex(height));
		}
		default: {
			final double totalWidth = size() * 4;
			final double width = size();
			final double height = size();
			return new Shape(new CenteredText(block(width, height), totalWidth),
					"centered " + hex(totalWidth) + " " + hex(width) + " " + hex(height));
		}
		}
	}

	private static final class Op {
		final UTranslate first;
		final UTranslate second;
		final UStroke stroke;
		final Shape shape;

		Op(UTranslate first, UTranslate second, UStroke stroke, Shape shape) {
			this.first = first;
			this.second = second;
			this.stroke = stroke;
			this.shape = shape;
		}

		void draw(UGraphic ug) {
			ug = ug.apply(first).apply(second);
			if (stroke != null)
				ug = ug.apply(stroke);
			ug.draw(shape.shape);
		}
	}

	private void scene() {
		final List<Op> ops = new ArrayList<>();
		final int count = 2 + random.nextInt(12);
		for (int i = 0; i < count; i++) {
			final double x = coordinate();
			final double y = coordinate();
			final double split = random.nextInt(3) == 0 ? random.nextInt(100) / 10.0 : random.nextInt(50);
			final UTranslate first = new UTranslate(split, x < 200 ? -split : split);
			final UTranslate second = new UTranslate(x - split, x < 200 ? y + split : y - split);
			final UStroke stroke = random.nextInt(4) == 0 ? UStroke.withThickness(1.5) : null;
			ops.add(new Op(first, second, stroke, shape()));
		}
		final double width = 400 + random.nextInt(100);
		final double height = 400 + random.nextInt(100);
		final TextBlock scene = new TextBlock() {
			public XDimension2D calculateDimension(StringBounder stringBounder) {
				return new XDimension2D(width, height);
			}

			public void drawU(UGraphic ug) {
				for (Op op : ops)
					op.draw(ug);
			}
		};
		out.println("scene " + hex(width) + " " + hex(height));
		for (Op op : ops) {
			final String stroke = op.stroke == null ? "-" : hex(op.stroke.getThickness());
			out.println("  " + at(op.first) + " " + at(op.second) + " " + stroke + " " + op.shape.description);
		}
		compress("ON_X", CompressionXorYBuilder.build(CompressionMode.ON_X, scene));
		compress("ON_Y", CompressionXorYBuilder.build(CompressionMode.ON_Y, scene));
		compress("ON_X ON_Y", CompressionXorYBuilder.build(CompressionMode.ON_Y,
				CompressionXorYBuilder.build(CompressionMode.ON_X, scene)));
	}

	private void compress(String passes, TextBlock compressed) {
		out.println(passes);
		final XDimension2D dimension = compressed.calculateDimension(stringBounder);
		out.println("  dimension " + hex(dimension.getWidth()) + " " + hex(dimension.getHeight()));
		final MinMax minMax = compressed.getMinMax(stringBounder);
		out.println("  minmax " + hex(minMax.getMinX()) + " " + hex(minMax.getMinY()) + " " + hex(minMax.getMaxX())
				+ " " + hex(minMax.getMaxY()));
		final List<String> lines = new ArrayList<>();
		compressed.drawU(new Recorder(stringBounder, UTranslate.none(), null, lines));
		for (String line : lines)
			out.println("  " + line);
	}

	/** Lists the primitives it receives with their absolute position. */
	private static final class Recorder extends UGraphicNo {
		private final UStroke stroke;
		private final List<String> lines;

		Recorder(StringBounder stringBounder, UTranslate translate, UStroke stroke, List<String> lines) {
			super(stringBounder, translate);
			this.stroke = stroke;
			this.lines = lines;
		}

		public UGraphic apply(UChange change) {
			if (change instanceof UTranslate)
				return new Recorder(getStringBounder(), getTranslate().compose((UTranslate) change), stroke, lines);
			if (change instanceof UStroke)
				return new Recorder(getStringBounder(), getTranslate(), (UStroke) change, lines);
			return this;
		}

		public void draw(UShape shape) {
			final String position = at(getTranslate());
			final String line;
			if (shape instanceof URectangle) {
				final URectangle rect = (URectangle) shape;
				line = "rect " + position + " " + hex(rect.getWidth()) + " " + hex(rect.getHeight());
			} else if (shape instanceof ULine) {
				final ULine uline = (ULine) shape;
				line = "line " + position + " " + hex(uline.getDX()) + " " + hex(uline.getDY());
			} else if (shape instanceof UPolygon) {
				line = "polygon " + position;
			} else if (shape instanceof UEllipse) {
				line = "ellipse " + position;
			} else if (shape instanceof UText) {
				line = "text " + position + " " + ((UText) shape).getText();
			} else if (shape instanceof UPath) {
				line = "path " + position;
			} else if (shape instanceof UEmpty) {
				line = "empty " + position;
			} else {
				line = shape.getClass().getSimpleName() + " " + position;
			}
			lines.add(stroke == null ? line : line + " stroke " + hex(stroke.getThickness()));
		}
	}
}
