import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import net.sourceforge.plantuml.BlockUml;
import net.sourceforge.plantuml.SourceStringReader;
import net.sourceforge.plantuml.activitydiagram3.ActivityDiagram3;
import net.sourceforge.plantuml.activitydiagram3.Branch;
import net.sourceforge.plantuml.activitydiagram3.Instruction;
import net.sourceforge.plantuml.activitydiagram3.InstructionBreak;
import net.sourceforge.plantuml.activitydiagram3.InstructionEnd;
import net.sourceforge.plantuml.activitydiagram3.InstructionFork;
import net.sourceforge.plantuml.activitydiagram3.InstructionGoto;
import net.sourceforge.plantuml.activitydiagram3.InstructionGroup;
import net.sourceforge.plantuml.activitydiagram3.InstructionIf;
import net.sourceforge.plantuml.activitydiagram3.InstructionLabel;
import net.sourceforge.plantuml.activitydiagram3.InstructionList;
import net.sourceforge.plantuml.activitydiagram3.InstructionRepeat;
import net.sourceforge.plantuml.activitydiagram3.InstructionSimple;
import net.sourceforge.plantuml.activitydiagram3.InstructionSplit;
import net.sourceforge.plantuml.activitydiagram3.InstructionSpot;
import net.sourceforge.plantuml.activitydiagram3.InstructionStart;
import net.sourceforge.plantuml.activitydiagram3.InstructionStop;
import net.sourceforge.plantuml.activitydiagram3.InstructionSwitch;
import net.sourceforge.plantuml.activitydiagram3.InstructionWhile;
import net.sourceforge.plantuml.activitydiagram3.LinkRendering;
import net.sourceforge.plantuml.activitydiagram3.PositionedNote;
import net.sourceforge.plantuml.activitydiagram3.ftile.BoxStyle;
import net.sourceforge.plantuml.activitydiagram3.ftile.Swimlane;
import net.sourceforge.plantuml.activitydiagram3.ftile.Swimlanes;
import net.sourceforge.plantuml.core.Diagram;
import net.sourceforge.plantuml.decoration.HtmlColorAndStyle;
import net.sourceforge.plantuml.decoration.Rainbow;
import net.sourceforge.plantuml.decoration.symbol.USymbol;
import net.sourceforge.plantuml.decoration.symbol.USymbols;
import net.sourceforge.plantuml.klimt.color.ColorType;
import net.sourceforge.plantuml.klimt.color.Colors;
import net.sourceforge.plantuml.klimt.color.HColor;
import net.sourceforge.plantuml.klimt.creole.Display;
import net.sourceforge.plantuml.stereo.Stereogroup;
import net.sourceforge.plantuml.stereo.Stereotype;
import net.sourceforge.plantuml.url.Url;

/**
 * Dumps the instruction tree PlantUML's activity diagram commands build from each source given, with the
 * swimlanes, for the exact comparison in crates/rockuml/src/diagram/activity3/tests.rs.
 */
public class ModelDump {

	private final PrintStream out;

	private ModelDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			final ModelDump dump = new ModelDump(out);
			out.println("# Generated by tools/oracle/activity-unit/model.sh from ModelDump.java; do not edit.");
			for (int i = 2; i < args.length; i++)
				dump.run(args[1], args[i]);
		}
	}

	private void run(String root, String file) throws Exception {
		final String text = new String(Files.readAllBytes(Paths.get(root, file)), StandardCharsets.UTF_8);
		final List<BlockUml> blocks = new SourceStringReader(text).getBlocks();
		final Diagram diagram = blocks.get(0).getDiagram();
		if (diagram instanceof ActivityDiagram3 == false)
			return;
		final ActivityDiagram3 activity = (ActivityDiagram3) diagram;
		final Swimlanes swimlanes = (Swimlanes) field(activity, "swimlanes");
		out.println("=== " + file);
		@SuppressWarnings("unchecked")
		final List<Swimlane> lanes = (List<Swimlane>) field(swimlanes, "swimlanesRaw");
		for (Swimlane lane : lanes)
			out.println("lane " + quoted(lane.getName()) + " display=" + display(lane.getDisplay())
					+ colors(lane.getColors()));
		out.println("next=" + link(swimlanes.nextLinkRenderer()) + " current="
				+ swimlanes.getCurrent().getClass().getSimpleName());
		list("root", (InstructionList) field(swimlanes, "root"), 0);
	}

	private void line(int depth, String text) {
		final StringBuilder sb = new StringBuilder();
		for (int i = 0; i < depth; i++)
			sb.append("  ");
		out.println(sb.append(text));
	}

	private void list(String name, InstructionList list, int depth) throws Exception {
		line(depth, name + " lane=" + lane((Swimlane) field(list, "defaultSwimlane")) + " out="
				+ link((LinkRendering) field(list, "outlinkRendering")));
		notes(list.getPositionedNotes(), depth + 1);
		@SuppressWarnings("unchecked")
		final List<Instruction> all = (List<Instruction>) field(list, "all");
		for (Instruction ins : all)
			instruction(ins, depth + 1);
	}

	private void notes(Collection<PositionedNote> notes, int depth) {
		for (PositionedNote note : notes)
			line(depth, note(note));
	}

	private static String note(PositionedNote note) {
		return "note " + note.getNotePosition() + " " + note.getType() + " " + display(note.getDisplay()) + " lane="
				+ lane(note.getSwimlaneNote()) + colors(note.getColors()) + stereo(note.getStereotype());
	}

	private void instruction(Instruction ins, int depth) throws Exception {
		if (ins instanceof InstructionSimple) {
			final InstructionSimple simple = (InstructionSimple) ins;
			line(depth, "simple " + display((Display) field(ins, "label")) + " lane=" + lane(simple.getSwimlaneIn())
					+ " box=" + box((BoxStyle) field(ins, "boxStyle")) + " in=" + link(ins.getInLinkRendering())
					+ colors((Colors) field(ins, "colors")) + stereo((Stereotype) field(ins, "stereotype"))
					+ url((Url) field(ins, "url")) + (simple.isKilled() ? " killed" : ""));
			notes(simple.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionSpot) {
			final InstructionSpot spot = (InstructionSpot) ins;
			line(depth, "spot " + quoted((String) field(ins, "spot")) + " lane=" + lane(spot.getSwimlaneIn())
					+ " in=" + link(ins.getInLinkRendering()) + color("color", (HColor) field(ins, "color"))
					+ ((Boolean) field(ins, "killed") ? " killed" : ""));
			notes(spot.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionStart) {
			final InstructionStart start = (InstructionStart) ins;
			line(depth, "start lane=" + lane(start.getSwimlaneIn()) + " in=" + link(ins.getInLinkRendering())
					+ colors((Colors) field(ins, "colors")));
			notes(start.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionStop) {
			final InstructionStop stop = (InstructionStop) ins;
			line(depth, "stop lane=" + lane(stop.getSwimlaneIn()) + " in=" + link(ins.getInLinkRendering())
					+ colors((Colors) field(ins, "colors")));
			notes(stop.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionEnd) {
			final InstructionEnd end = (InstructionEnd) ins;
			line(depth, "end lane=" + lane(end.getSwimlaneIn()) + " in=" + link(ins.getInLinkRendering())
					+ colors((Colors) field(ins, "colors")));
			notes(end.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionBreak) {
			final InstructionBreak brk = (InstructionBreak) ins;
			line(depth, "break lane=" + lane(brk.getSwimlaneIn()) + " in=" + link(ins.getInLinkRendering()));
			notes(brk.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionGoto) {
			final InstructionGoto go = (InstructionGoto) ins;
			line(depth, "goto " + quoted((String) field(ins, "name")) + " lane=" + lane(go.getSwimlaneIn()));
			notes(go.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionLabel) {
			final InstructionLabel label = (InstructionLabel) ins;
			line(depth, "label " + quoted((String) field(ins, "name")) + " lane=" + lane(label.getSwimlaneIn()));
			notes(label.getPositionedNotes(), depth + 1);
		} else if (ins instanceof InstructionIf) {
			instructionIf((InstructionIf) ins, depth);
		} else if (ins instanceof InstructionSwitch) {
			instructionSwitch((InstructionSwitch) ins, depth);
		} else if (ins instanceof InstructionWhile) {
			instructionWhile((InstructionWhile) ins, depth);
		} else if (ins instanceof InstructionRepeat) {
			instructionRepeat((InstructionRepeat) ins, depth);
		} else if (ins instanceof InstructionFork) {
			instructionFork((InstructionFork) ins, depth);
		} else if (ins instanceof InstructionSplit) {
			instructionSplit((InstructionSplit) ins, depth);
		} else if (ins instanceof InstructionGroup) {
			instructionGroup((InstructionGroup) ins, depth);
		} else {
			throw new IllegalStateException(ins.getClass().getName());
		}
	}

	private void instructionIf(InstructionIf ins, int depth) throws Exception {
		line(depth, "if lane=" + lane(ins.getSwimlaneIn()) + " in=" + link(ins.getInLinkRendering()) + " out="
				+ link((LinkRendering) field(ins, "outColor")) + url((Url) field(ins, "url"))
				+ stereo((Stereotype) field(ins, "stereotype")) + ((Boolean) field(ins, "endifCalled") ? " endif" : ""));
		notes(ins.getPositionedNotes(), depth + 1);
		@SuppressWarnings("unchecked")
		final List<Branch> thens = (List<Branch>) field(ins, "thens");
		for (Branch branch : thens)
			branch("then", branch, depth + 1);
		final Branch elseBranch = (Branch) field(ins, "elseBranch");
		if (elseBranch != null)
			branch("else", elseBranch, depth + 1);
	}

	private void instructionSwitch(InstructionSwitch ins, int depth) throws Exception {
		line(depth, "switch lane=" + lane(ins.getSwimlaneIn()) + " test=" + display((Display) field(ins, "labelTest"))
				+ " in=" + link(ins.getInLinkRendering())
				+ " colors=[" + colors((Colors) field(ins, "colors")) + " ] endColors=["
				+ colors((Colors) field(ins, "endColors")) + " ]");
		notes(ins.getPositionedNotes(), depth + 1);
		@SuppressWarnings("unchecked")
		final List<Branch> switches = (List<Branch>) field(ins, "switches");
		for (Branch branch : switches)
			branch("case", branch, depth + 1);
	}

	private void branch(String name, Branch branch, int depth) throws Exception {
		final LinkRendering special = branch.getSpecial();
		line(depth, name + " test=" + display(branch.getLabelTest()) + " positive="
				+ link((LinkRendering) field(branch, "labelPositive")) + " inlabel="
				+ link((LinkRendering) field(branch, "inlabel")) + " inlink="
				+ link((LinkRendering) field(branch, "inlinkRendering")) + " special=" + link(special)
				+ color("color", (HColor) field(branch, "color")) + " specialColors=["
				+ colors((Colors) field(branch, "specialColors")) + " ]");
		list("list", (InstructionList) field(branch, "list"), depth + 1);
	}

	private void instructionWhile(InstructionWhile ins, int depth) throws Exception {
		line(depth, "while lane=" + lane((Swimlane) field(ins, "swimlane")) + " test="
				+ display((Display) field(ins, "test")) + " yes=" + display((Display) field(ins, "yes")) + " in="
				+ link(ins.getInLinkRendering()) + " out=" + link((LinkRendering) field(ins, "outColor"))
				+ color("color", (HColor) field(ins, "color")) + " backward="
				+ display((Display) field(ins, "backward")) + " box=" + box((BoxStyle) field(ins, "boxStyle"))
				+ stereo((Stereotype) field(ins, "stereotype")) + " incoming1="
				+ link((LinkRendering) field(ins, "incoming1")) + " incoming2="
				+ link((LinkRendering) field(ins, "incoming2")) + flag(ins, "testCalled") + flag(ins, "backwardCalled")
				+ flag(ins, "killed"));
		notes(ins.getPositionedNotes(), depth + 1);
		final Instruction special = (Instruction) field(ins, "specialOut");
		if (special != null) {
			line(depth + 1, "special");
			instruction(special, depth + 2);
		}
		list("list", (InstructionList) field(ins, "repeatList"), depth + 1);
	}

	private void instructionRepeat(InstructionRepeat ins, int depth) throws Exception {
		line(depth, "repeat lane=" + lane((Swimlane) field(ins, "swimlane")) + " laneOut="
				+ lane((Swimlane) field(ins, "swimlaneOut")) + " laneBackward="
				+ lane((Swimlane) field(ins, "swimlaneBackward")) + " in=" + link(ins.getInLinkRendering())
				+ " start=" + display((Display) field(ins, "startLabel")) + " boxIn="
				+ box((BoxStyle) field(ins, "boxStyleIn")) + " stereoLoop="
				+ stereogroup((Stereogroup) field(ins, "stereogroupLoop")) + " backward="
				+ display((Display) field(ins, "backward")) + " box=" + box((BoxStyle) field(ins, "boxStyle"))
				+ " stereoBack=" + quoted(stereoText((Stereotype) field(ins, "stereotypeBack"))) + " test="
				+ display((Display) field(ins, "test")) + " yes=" + display((Display) field(ins, "yes")) + " out="
				+ display((Display) field(ins, "out")) + " incoming1=" + link((LinkRendering) field(ins, "incoming1"))
				+ " incoming2=" + link((LinkRendering) field(ins, "incoming2")) + " end="
				+ link((LinkRendering) field(ins, "endRepeatLinkRendering")) + " stereo2="
				+ stereogroup((Stereogroup) field(ins, "stereotype2")) + flag(ins, "testCalled")
				+ flag(ins, "killed"));
		@SuppressWarnings("unchecked")
		final List<PositionedNote> backwardNotes = (List<PositionedNote>) field(ins, "backwardNotes");
		for (PositionedNote note : backwardNotes)
			line(depth + 1, "backward " + note(note));
		list("list", (InstructionList) field(ins, "repeatList"), depth + 1);
	}

	private void instructionFork(InstructionFork ins, int depth) throws Exception {
		line(depth, "fork laneIn=" + lane(ins.getSwimlaneIn()) + " laneOut=" + lane(ins.getSwimlaneOut()) + " in="
				+ link(ins.getInLinkRendering()) + " style=" + field(ins, "style") + " label="
				+ quoted((String) field(ins, "label")) + flag(ins, "finished") + colors((Colors) field(ins, "colors")));
		notes(ins.getPositionedNotes(), depth + 1);
		@SuppressWarnings("unchecked")
		final List<InstructionList> forks = (List<InstructionList>) field(ins, "forks");
		for (InstructionList list : forks)
			list("list", list, depth + 1);
	}

	private void instructionSplit(InstructionSplit ins, int depth) throws Exception {
		line(depth, "split laneIn=" + lane((Swimlane) field(ins, "swimlaneIn")) + " laneOut="
				+ lane(ins.getSwimlaneOut()) + " in=" + link(ins.getInLinkRendering())
				+ colors((Colors) field(ins, "colors")));
		@SuppressWarnings("unchecked")
		final List<InstructionList> splits = (List<InstructionList>) field(ins, "splits");
		for (InstructionList list : splits)
			list("list", list, depth + 1);
	}

	private void instructionGroup(InstructionGroup ins, int depth) throws Exception {
		line(depth, "group " + symbol((USymbol) field(ins, "type")) + " title=" + display((Display) field(ins, "title"))
				+ " in=" + link(ins.getInLinkRendering()) + color("back", (HColor) field(ins, "backColor")));
		final PositionedNote note = (PositionedNote) field(ins, "note");
		if (note != null)
			line(depth + 1, note(note));
		list("list", (InstructionList) field(ins, "list"), depth + 1);
	}

	private static String flag(Object owner, String name) throws Exception {
		return (Boolean) field(owner, name) ? " " + name : "";
	}

	private static Object field(Object owner, String name) throws Exception {
		for (Class<?> type = owner.getClass(); type != null; type = type.getSuperclass())
			for (Field field : type.getDeclaredFields())
				if (field.getName().equals(name)) {
					field.setAccessible(true);
					return field.get(owner);
				}
		throw new NoSuchFieldException(owner.getClass().getName() + "." + name);
	}

	/** A link's label and colours, each colour as arrow/head/style; `null` for a missing link. */
	private static String link(LinkRendering link) {
		if (link == null)
			return "null";
		return "(" + display(link.getDisplay()) + " " + rainbow(link.getRainbow()) + ")";
	}

	private static String rainbow(Rainbow rainbow) {
		final StringBuilder sb = new StringBuilder("[");
		for (HtmlColorAndStyle color : rainbow.getColors()) {
			if (sb.length() > 1)
				sb.append(",");
			sb.append(asString(color.getArrowColor())).append("/").append(asString(color.getArrowHeadColor()))
					.append("/").append(color.getStyle());
		}
		sb.append("]");
		if (rainbow.getColorArrowSeparationSpace() != 0)
			sb.append("~").append(rainbow.getColorArrowSeparationSpace());
		return sb.toString();
	}

	private static String lane(Swimlane lane) {
		return lane == null ? "null" : quoted(lane.getName());
	}

	private static String box(BoxStyle box) {
		return box == null ? "null" : String.valueOf(box.name());
	}

	private static String stereo(Stereotype stereotype) {
		return stereotype == null ? "" : " stereo=" + quoted(stereotype.toString());
	}

	private static String stereoText(Stereotype stereotype) {
		return stereotype == null ? null : stereotype.toString();
	}

	private static String stereogroup(Stereogroup stereogroup) {
		if (stereogroup == null)
			return "null";
		final Stereotype stereotype = stereogroup.buildStereotype();
		return quoted(stereotype == null ? null : stereotype.toString());
	}

	private static String url(Url url) {
		return url == null ? "" : " url=" + quoted(url.getUrl());
	}

	private static String color(String name, HColor color) {
		return color == null ? "" : " " + name + "=" + asString(color);
	}

	private static String asString(HColor color) {
		return color == null ? "null" : color.asString();
	}

	/** Each colour set, by its type, and the line style; nothing when none is. */
	private static String colors(Colors colors) {
		final StringBuilder sb = new StringBuilder();
		if (colors == null)
			return "";
		for (ColorType type : ColorType.values())
			if (colors.getColor(type) != null)
				sb.append(" ").append(type).append("=").append(colors.getColor(type).asString());
		if (colors.getSpecificLineStroke() != null)
			sb.append(" stroke=").append(colors.getSpecificLineStroke());
		return sb.toString();
	}

	private static String display(Display display) {
		if (display == null || Display.isNull(display))
			return "null";
		final List<String> lines = new ArrayList<>();
		for (CharSequence line : display)
			lines.add(line.toString());
		return quoted(String.join("\n", lines));
	}

	private static String quoted(String s) {
		if (s == null)
			return "null";
		return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
	}

	private static String symbol(USymbol symbol) throws Exception {
		if (symbol == null)
			return "null";
		for (Field field : USymbols.class.getFields())
			if (field.get(null) == symbol)
				return field.getName();
		return symbol.getClass().getSimpleName();
	}
}
