//! Replays tests/data/extremity.txt, PlantUML's own drawing of every link decoration (generated by
//! tools/oracle/cuca-unit/extremity.sh), and compares the shapes exactly.

use std::cell::RefCell;
use std::rc::Rc;

use regex::Regex;

use super::*;
use crate::color::{ColorMapper, HColor, XColor};
use crate::java;
use crate::klimt::debug::{DebugHeader, StringBounderDebug, UGraphicDebug};
use crate::klimt::geom::XDimension2D;
use crate::klimt::svg::{SvgOption, UGraphicSvg};
use crate::klimt::ugraphic::{UGraphicBackend, UStroke};

const FIXTURE: &str = include_str!("../../../tests/data/extremity.txt");

const LINE: HColor = HColor::Simple(XColor::from_rgb(0x18_18_18));
const BACKGROUND: HColor = HColor::Simple(XColor::from_rgb(0xF1_F1_F1));

fn factory(name: &str) -> Box<dyn ExtremityFactory> {
    match name {
        "Plus" => Box::new(ExtremityFactoryPlus::new(BACKGROUND)),
        "ExtendsLike(false)" => Box::new(ExtremityFactoryExtendsLike::new(BACKGROUND, false)),
        "ExtendsLike(true)" => Box::new(ExtremityFactoryExtendsLike::new(BACKGROUND, true)),
        "HalfArrow(1)" => Box::new(ExtremityFactoryHalfArrow::new(1)),
        "HalfArrow(-1)" => Box::new(ExtremityFactoryHalfArrow::new(-1)),
        "Triangle(8,3,8)" => Box::new(ExtremityFactoryTriangle::new(8.0, 3.0, 8.0)),
        "Triangle(18,6,18)" => Box::new(ExtremityFactoryTriangle::new(18.0, 6.0, 18.0)),
        "Crowfoot" => Box::new(ExtremityFactoryCrowfoot),
        "CircleCrowfoot" => Box::new(ExtremityFactoryCircleCrowfoot),
        "LineCrowfoot" => Box::new(ExtremityFactoryLineCrowfoot),
        "CircleLine" => Box::new(ExtremityFactoryCircleLine),
        "DoubleLine" => Box::new(ExtremityFactoryDoubleLine),
        "CircleCross" => Box::new(ExtremityFactoryCircleCross::new(BACKGROUND)),
        "Arrow" => Box::new(ExtremityFactoryArrow),
        "ArrowAndCircle" => Box::new(ExtremityFactoryArrowAndCircle::new(BACKGROUND)),
        "NotNavigable" => Box::new(ExtremityFactoryNotNavigable),
        "Diamond(false)" => Box::new(ExtremityFactoryDiamond::new(false)),
        "Diamond(true)" => Box::new(ExtremityFactoryDiamond::new(true)),
        "Circle(false)" => Box::new(ExtremityFactoryCircle::new(false, BACKGROUND)),
        "Circle(true)" => Box::new(ExtremityFactoryCircle::new(true, BACKGROUND)),
        "Square" => Box::new(ExtremityFactorySquare::new(BACKGROUND)),
        "Parenthesis" => Box::new(ExtremityFactoryParenthesis),
        "CircleConnect" => Box::new(ExtremityFactoryCircleConnect::new(BACKGROUND)),
        _ => panic!("unknown factory {name}"),
    }
}

/// A case of the fixture: its header words and the lines PlantUML wrote for it.
struct Case<'a> {
    header: &'a str,
    words: Vec<&'a str>,
    expected: String,
}

impl Case<'_> {
    fn extremity(&self) -> Box<dyn Extremity> {
        let double = |hex: &str| f64::from_bits(u64::from_str_radix(hex, 16).expect("hex bits"));
        let p0 = XPoint2D::new(double(self.words[2]), double(self.words[3]));
        factory(self.words[1]).create_udrawable(p0, double(self.words[4]))
    }
}

fn cases(kind: &str) -> Vec<Case<'_>> {
    let mut cases = Vec::new();
    let mut lines = FIXTURE.lines();
    while let Some(header) = lines.next() {
        if header.starts_with('#') {
            continue;
        }
        let words: Vec<&str> = header.split(' ').collect();
        let body: Vec<&str> = lines.by_ref().take_while(|line| *line != "end").collect();
        if words[0] == kind {
            cases.push(Case {
                header,
                words,
                expected: body.iter().flat_map(|&line| [line, "\n"]).collect(),
            });
        }
    }
    cases
}

fn drawn_on<B: UGraphicBackend + 'static>(
    backend: B,
    draw: impl FnOnce(&UGraphic),
) -> Rc<RefCell<B>> {
    let backend = Rc::new(RefCell::new(backend));
    let ug = UGraphic::new(backend.clone(), Rc::new(StringBounderDebug), HColor::WHITE);
    draw(&ug.with_backcolor(HColor::NONE).with_color(LINE));
    backend
}

fn assert_all_match(mismatches: &[String], total: usize) {
    assert!(total > 0, "the fixture has no such case");
    assert!(
        mismatches.is_empty(),
        "{} of {total} cases differ from PlantUML; the first:\n{}",
        mismatches.len(),
        mismatches[..mismatches.len().min(3)].join("\n")
    );
}

#[test]
fn decorations_draw_the_shapes_plantuml_draws() {
    let cases = cases("case");
    let mut mismatches = Vec::new();
    for case in &cases {
        let extremity = case.extremity();
        let debug = drawn_on(UGraphicDebug::new(String::new()), |ug| {
            match case.words[5] {
                "hollow" => extremity.draw_u(ug),
                "filled" => extremity.draw_u(&ug.with_backcolor(LINE)),
                "thick" => extremity.draw_u(&ug.with_stroke(UStroke::with_thickness(2.5))),
                variant => panic!("unknown variant {variant}"),
            }
        });
        let document = debug.borrow().document(&DebugHeader {
            dimension: XDimension2D::default(),
            scale_factor: 1.0,
            seed: 0,
            svg_link_target: None,
            hover_path_color_rgb: None,
            preserve_aspect_ratio: "none".to_owned(),
        });
        let shapes = &document[document.find("\n\n").expect("a header") + 2..];
        let actual = format!(
            "decorationLength: {}\n{shapes}",
            java::double_to_string(extremity.decoration_length())
        );
        if actual != case.expected {
            mismatches.push(format!(
                "{}\nexpected:\n{}actual:\n{actual}",
                case.header, case.expected
            ));
        }
    }
    assert_all_match(&mismatches, cases.len());
}

#[test]
fn arcs_draw_the_svg_paths_plantuml_draws() {
    let path = Regex::new("<path[^>]*/>").unwrap();
    let cases = cases("svg");
    let mut mismatches = Vec::new();
    for case in &cases {
        let option = SvgOption {
            min_dim: XDimension2D::default(),
            backcolor: HColor::WHITE,
            scale: 1.0,
            preserve_aspect_ratio: "none".to_owned(),
            root_attributes: Vec::new(),
            link_target: None,
            color_mapper: ColorMapper::Identity,
        };
        let svg = UGraphicSvg::new(0, option, Rc::new(StringBounderDebug), None, false);
        let svg = drawn_on(svg, |ug| case.extremity().draw_u(ug));
        let document = svg.borrow_mut().take_document(None);
        let actual: String = path
            .find_iter(&document)
            .flat_map(|element| [element.as_str(), "\n"])
            .collect();
        if actual != case.expected {
            mismatches.push(format!(
                "{}\nexpected:\n{}actual:\n{actual}",
                case.header, case.expected
            ));
        }
    }
    assert_all_match(&mismatches, cases.len());
}
