[package]
name = "rockuml"
description = "PlantUML-compatible diagram engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
brotli-decompressor = "6.0.1"
jiff = "0.2.37"
regex = "1.13.1"
unicode-general-category = "1.1.0"
