[package]
name = "rockuml"
description = "PlantUML-compatible diagram engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "0.23.1"
brotli-decompressor = "6.0.1"
fancy-regex = "0.19.2"
flate2 = "1.1.10"
jiff = "0.2.37"
md5 = "0.8.1"
png = "0.18.1"
regex = "1.13.1"
resvg = { version = "0.48.1", default-features = false, features = ["text", "raster-images"] }
ttf-parser = "0.25.1"
unicode-general-category = "1.1.0"
