//! Cases only ever move from failing to passing: once recorded as passing, a failure is a regression.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

pub type Entry = (String, String);

pub fn load(path: &Path) -> BTreeSet<Entry> {
    fs::read_to_string(path)
        .unwrap_or_default()
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (kind, case_id) = line
                .split_once(' ')
                .expect("ratchet lines are `<kind> <case id>`");
            (kind.to_owned(), case_id.to_owned())
        })
        .collect()
}

pub fn save(path: &Path, entries: &BTreeSet<Entry>) {
    let mut content = String::from(
        "# Generated by the parity test with ROCKUML_PARITY_RECORD=1. Format: <kind> <case id>\n",
    );
    for (kind, case_id) in entries {
        writeln!(content, "{kind} {case_id}").unwrap();
    }
    fs::write(path, content).unwrap();
}
