import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import net.sourceforge.plantuml.BlockUml;
import net.sourceforge.plantuml.SourceStringReader;
import net.sourceforge.plantuml.abel.Entity;
import net.sourceforge.plantuml.abel.LeafType;
import net.sourceforge.plantuml.abel.Link;
import net.sourceforge.plantuml.core.Diagram;
import net.sourceforge.plantuml.decoration.symbol.USymbol;
import net.sourceforge.plantuml.decoration.symbol.USymbols;
import net.sourceforge.plantuml.descdiagram.DescriptionDiagram;
import net.sourceforge.plantuml.klimt.color.ColorType;
import net.sourceforge.plantuml.klimt.color.Colors;
import net.sourceforge.plantuml.klimt.drawing.debug.UGraphicDebug;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;
import net.sourceforge.plantuml.svek.Bibliotekon;
import net.sourceforge.plantuml.svek.GeneralImageBuilder;
import net.sourceforge.plantuml.svek.IEntityImage;
import net.sourceforge.plantuml.svek.Margins;

/**
 * Dumps what PlantUML's description diagram commands make of each source given (entities, groups and links), and
 * each leaf's image measured and drawn on the debug UGraphic, for the exact comparison in
 * crates/rockuml/src/diagram/description/tests.rs.
 */
public class DescriptionDump {

	private static final StringBounder BOUNDER = new UGraphicDebug(1, new XDimension2D(0, 0), null, null, 0, "none")
			.getStringBounder();

	private final PrintStream out;

	private DescriptionDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			final DescriptionDump dump = new DescriptionDump(out);
			out.println("# Generated by tools/oracle/cuca-unit/description.sh from DescriptionDump.java; do not edit.");
			for (int i = 2; i < args.length; i++)
				dump.run(args[1], args[i]);
		}
	}

	private void run(String root, String file) throws Exception {
		final String text = new String(Files.readAllBytes(Paths.get(root, file)), StandardCharsets.UTF_8);
		final List<BlockUml> blocks = new SourceStringReader(text).getBlocks();
		final Diagram diagram = blocks.get(0).getDiagram();
		if (diagram instanceof DescriptionDiagram == false)
			return;
		final DescriptionDiagram desc = (DescriptionDiagram) diagram;
		out.println("=== " + file);
		for (Entity group : desc.groups())
			out.println("group " + group.getUid() + " " + quoted(group.getQuark().getQualifiedName()) + " "
					+ group.getGroupType() + " " + symbol(group.getUSymbol()) + " " + describe(group));
		for (Entity leaf : desc.leafs())
			out.println("leaf " + leaf.getUid() + " " + quoted(leaf.getQuark().getQualifiedName()) + " "
					+ leaf.getLeafType() + " " + symbol(leaf.getUSymbol()) + " " + describe(leaf));
		for (Link link : desc.getLinks())
			out.println("link " + link.getUid() + " " + link.getEntity1().getUid() + " " + link.getEntity2().getUid()
					+ " " + link.getType().getDecor1() + " " + link.getType().getDecor2() + " "
					+ link.getType().getMiddleDecor() + " " + link.getType().getStroke3(null)
					+ (link.getType().isInvisible() ? " invisible" : "") + " length=" + link.getLength() + " label="
					+ quoted(link.getLabel() == null ? null : String.join("\n", lines(link.getLabel())))
					+ " q1=" + quoted(link.getQuantifier1()) + " q2=" + quoted(link.getQuantifier2()) + " "
					+ link.getLinkArrow() + (link.isInverted() ? " inverted" : "") + colors(link.getColors())
					+ " stereo=" + quoted(link.getStereotype() == null ? null
							: link.getStereotype().getLabel(net.sourceforge.plantuml.text.Guillemet.DOUBLE_COMPARATOR)));
		final Bibliotekon bibliotekon = new Bibliotekon(desc.getLinks());
		for (Entity leaf : desc.leafs()) {
			final LeafType type = leaf.getLeafType();
			if (leaf.isRemoved() || type == LeafType.NOTE)
				continue;
			final IEntityImage image = GeneralImageBuilder.createEntityImageBlock(leaf, false, desc, bibliotekon,
					null, desc.getLinks());
			bibliotekon.createNode(leaf, image, BOUNDER);
			image(leaf, image);
		}
	}

	private void image(Entity leaf, IEntityImage image) throws Exception {
		out.println("image " + leaf.getUid() + " " + image.getClass().getSimpleName());
		final XDimension2D dim = image.calculateDimension(BOUNDER);
		out.println("dimension: " + dim.getWidth() + " " + dim.getHeight());
		out.println("shape: " + image.getShapeType());
		final Margins shield = image.getShield(BOUNDER);
		if (shield.isZero() == false)
			out.println("shield: " + shield.getX1() + " " + shield.getX2() + " " + shield.getY1() + " "
					+ shield.getY2());
		if (image.getOverscanX(BOUNDER) != 0)
			out.println("overscan: " + image.getOverscanX(BOUNDER));
		final UGraphicDebug ug = new UGraphicDebug(1, dim, null, null, 0, "none");
		image.drawU(ug);
		final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
		ug.writeToStream(bytes, null, 96);
		final String[] lines = new String(bytes.toByteArray(), StandardCharsets.UTF_8).split("\n", -1);
		boolean inHeader = true;
		for (String line : lines) {
			if (inHeader) {
				inHeader = !line.isEmpty();
				continue;
			}
			if (line.startsWith("UGraphicDebug "))
				line = line.replaceFirst("^(UGraphicDebug \\S+) .*$", "$1 DATE");
			out.println(line);
		}
	}

	private static String describe(Entity entity) {
		final StringBuilder sb = new StringBuilder();
		sb.append("display=").append(quoted(String.join("\n", lines(entity.getDisplay()))));
		if (entity.getStereotype() != null)
			sb.append(" stereo=").append(quoted(entity.getStereotype().toString()));
		sb.append(colors(entity.getColors()));
		if (entity.getUrl99() != null)
			sb.append(" url=").append(quoted(entity.getUrl99().getUrl()));
		return sb.toString();
	}

	/** Each colour set, by its type, and the line style; nothing when none is. */
	private static String colors(Colors colors) {
		final StringBuilder sb = new StringBuilder();
		if (colors == null)
			return "";
		for (ColorType type : ColorType.values())
			if (colors.getColor(type) != null)
				sb.append(" ").append(type).append("=").append(colors.getColor(type).asString());
		if (colors.getSpecificLineStroke() != null)
			sb.append(" stroke=").append(colors.getSpecificLineStroke());
		return sb.toString();
	}

	private static List<String> lines(net.sourceforge.plantuml.klimt.creole.Display display) {
		final java.util.ArrayList<String> result = new java.util.ArrayList<>();
		if (display == null || net.sourceforge.plantuml.klimt.creole.Display.isNull(display))
			return result;
		for (CharSequence line : display)
			result.add(line.toString());
		return result;
	}

	private static String quoted(String s) {
		if (s == null)
			return "null";
		return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\"";
	}

	private static String symbol(USymbol symbol) throws Exception {
		if (symbol == null)
			return "null";
		for (Field field : USymbols.class.getFields())
			if (field.get(null) == symbol)
				return field.getName();
		return symbol.getClass().getSimpleName();
	}
}
