package net.sourceforge.plantuml.svek;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.atmp.CucaDiagram;
import net.sourceforge.plantuml.SourceStringReader;
import net.sourceforge.plantuml.abel.Entity;
import net.sourceforge.plantuml.abel.LeafType;
import net.sourceforge.plantuml.abel.Link;
import net.sourceforge.plantuml.abel.LinkArg;
import net.sourceforge.plantuml.decoration.LinkDecor;
import net.sourceforge.plantuml.decoration.LinkType;
import net.sourceforge.plantuml.klimt.UTranslate;
import net.sourceforge.plantuml.klimt.color.ColorType;
import net.sourceforge.plantuml.klimt.color.Colors;
import net.sourceforge.plantuml.klimt.creole.Display;
import net.sourceforge.plantuml.klimt.drawing.debug.UGraphicDebug;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.geom.MagneticBorder;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;
import net.sourceforge.plantuml.klimt.geom.XPoint2D;
import net.sourceforge.plantuml.klimt.geom.XRectangle2D;
import net.sourceforge.plantuml.klimt.shape.TextBlock;
import net.sourceforge.plantuml.sdot.SmetanaEdge;
import net.sourceforge.plantuml.style.ISkinParam;
import net.sourceforge.plantuml.svek.image.EntityImageNote;
import net.sourceforge.plantuml.svek.image.EntityImageNoteLink;
import net.sourceforge.plantuml.svek.image.EntityImageTips;

/**
 * Dumps the images of notes, drawn on the debug UGraphic, for the exact comparison in
 * crates/rockuml/src/diagram/cuca_commands/note/image_tests.rs. The Rust test rebuilds the same inputs from the
 * case names, so the cases below must stay in step with it. It sits in PlantUML's svek package to place the
 * nodes an opale note is drawn between.
 */
public class NoteDump {

	private static final StringBounder BOUNDER = new UGraphicDebug(1, new XDimension2D(0, 0), null, null, 0, "none")
			.getStringBounder();

	/** Each case: name, then the lines between @startuml and @enduml. */
	static final String[][] SOURCES = { //
			{ "plain", "note \"Simple note\" as N1" }, //
			{ "multi", "note as N1", "  Reads **tokens** and", "  builds an //AST//.", "  ----", "  Second block",
					"  == Title ==", "  last", "end note" }, //
			{ "color", "note \"Colored\" as N1 #pink" }, //
			{ "styled", "<style>", "note {", "  BackGroundColor lightblue", "  LineColor red", "  LineThickness 2",
					"}", ".warn {", "  BackGroundColor yellow", "}", "</style>", "note \"Styled\" as N1 <<warn>>",
					"note \"Plain\" as N2" }, //
			{ "round", "skinparam roundCorner 12", "note \"Rounded\\nnote\" as N1" }, //
			{ "empty", "note as N1", "", "end note" }, //
			{ "wrap", "<style>", "note {", "  MaximumWidth 60", "  HorizontalAlignment center", "}", "</style>",
					"note \"A long note that should wrap over several lines\" as N1" }, //
			{ "state", "state S", "note \"In a state diagram\" as N1" }, //
			{ "usecase", "usecase U", "note \"In a description diagram\" as N1" } };

	/** Link ends, relative to the note's corner, and the force the other entity's border exerts. */
	static final double[][] OPALE = { //
			{ 30, 33, 30, 100, 0, 0 }, // below, from the note
			{ 30, 100, 30, 33, 0, 0 }, // below, towards the note
			{ 30, 0, 40, -60, 0, 0 }, // above
			{ 0, 10, -80, 12, 0, 0 }, // left
			{ 70, 10, 150, -5, 0, 0 }, // right
			{ 70, 10, 150, 40, 3, -4 }, // right, pulled by the other border
			{ -20, 200, 10, 23, 0, 0 } }; // far below left, towards the note

	static final XPoint2D NOTE_CORNER = new XPoint2D(100, 50);

	private final PrintStream out;

	private NoteDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new NoteDump(out).run();
		}
	}

	private static CucaDiagram parse(String[] lines) {
		final StringBuilder source = new StringBuilder("@startuml\n");
		for (String line : Arrays.copyOfRange(lines, 1, lines.length))
			source.append(line).append('\n');
		source.append("@enduml\n");
		return (CucaDiagram) new SourceStringReader(source.toString()).getBlocks().get(0).getDiagram();
	}

	private static Entity named(CucaDiagram diagram, String name) {
		for (Entity leaf : diagram.leafs())
			if (leaf.getName().equals(name))
				return leaf;
		throw new IllegalArgumentException(name);
	}

	private void run() throws Exception {
		out.println("# Generated by tools/oracle/cuca-unit/note.sh from NoteDump.java; do not edit.");
		for (String[] source : SOURCES) {
			final CucaDiagram diagram = parse(source);
			for (Entity leaf : diagram.leafs())
				if (leaf.getLeafType() == LeafType.NOTE)
					dump("note " + source[0] + " " + leaf.getName(), new EntityImageNote(leaf));
		}
		for (String kase : Arrays.asList("plain", "round", "multi"))
			for (double[] opale : OPALE)
				dumpOpale(kase, opale);
		dumpLinkNotes();
		dumpTips();
	}

	private void dumpOpale(String kase, double[] opale) throws Exception {
		final String[] source = Arrays.stream(SOURCES).filter(s -> s[0].equals(kase)).findFirst().get();
		final CucaDiagram diagram = parse(source);
		final Entity note = named(diagram, "N1");
		final EntityImageNote image = new EntityImageNote(note);
		final ISkinParam skinParam = diagram.getSkinParam();
		final Link link = new Link(null, diagram, skinParam.getCurrentStyleBuilder(), note, note,
				new LinkType(LinkDecor.NONE, LinkDecor.NONE), LinkArg.noDisplay(1));
		final XPoint2D start = new XPoint2D(NOTE_CORNER.getX() + opale[0], NOTE_CORNER.getY() + opale[1]);
		final XPoint2D end = new XPoint2D(NOTE_CORNER.getX() + opale[2], NOTE_CORNER.getY() + opale[3]);
		final SmetanaEdge edge = new SmetanaEdge(link, null, null, null, null, null, null, null,
				new Bibliotekon(diagram.getLinks()), skinParam) {
			@Override
			public XPoint2D getStartPoint() {
				return start;
			}

			@Override
			public XPoint2D getEndPoint() {
				return end;
			}
		};
		final SvekNode node = new SvekNode(note, image, new ColorSequence(), BOUNDER);
		node.moveDelta(NOTE_CORNER.getX(), NOTE_CORNER.getY());
		final UTranslate force = new UTranslate(opale[4], opale[5]);
		final EntityImageNote otherImage = new EntityImageNote(note) {
			@Override
			public MagneticBorder getMagneticBorder() {
				return (stringBounder, position) -> force;
			}
		};
		final SvekNode other = new SvekNode(note, otherImage, new ColorSequence(), BOUNDER);
		final Map<Link, SmetanaEdge> edges = new HashMap<>();
		edges.put(link, edge);
		image.setOpaleLink(link, node, other, edges);
		final StringBuilder header = new StringBuilder("opale " + kase);
		for (double value : opale)
			header.append(' ').append(value);
		dump(header.toString(), image);
	}

	/** Each case: lines, then the colour or "-". */
	static final String[][] LINK_NOTES = { //
			{ "-", "one or more" }, //
			{ "#lightyellow", "ordered", "quantity" } };

	private void dumpLinkNotes() throws Exception {
		final CucaDiagram diagram = parse(SOURCES[0]);
		final ISkinParam skinParam = diagram.getSkinParam();
		for (String[] kase : LINK_NOTES) {
			final Colors colors = kase[0].equals("-") ? Colors.empty()
					: new Colors(kase[0], skinParam.getIHtmlColorSet(), ColorType.BACK);
			final Display display = Display.create(Arrays.asList(Arrays.copyOfRange(kase, 1, kase.length)));
			dump("link " + String.join("|", kase),
					new EntityImageNoteLink(display, colors, skinParam, skinParam.getCurrentStyleBuilder()));
		}
	}

	/** Where the tips and their class are laid out. */
	static final XPoint2D TIPS_CORNER = new XPoint2D(300, 40);
	static final XPoint2D CLASS_CORNER = new XPoint2D(100, 20);

	/**
	 * The tips of both sides of a class, drawn next to members placed by hand: class images are not the subject
	 * here.
	 */
	private void dumpTips() throws Exception {
		final CucaDiagram diagram = parse(new String[] { "tips", "class Thread {", "  +start()", "  priority : int",
				"}", "note \"placeholder\" as N9", "note right of Thread::start", "  spawns the", "  OS thread",
				"end note", "note right of Thread::priority #pink", "  1 to 10", "end note",
				"note left of Thread::start", "  starts", "end note" });
		final Entity thread = named(diagram, "Thread");
		for (String side : Arrays.asList("RIGHT", "LEFT")) {
			final Bibliotekon bibliotekon = new Bibliotekon(diagram.getLinks());
			final Entity tips = named(diagram, "Thread$$$" + side);
			final EntityImageTips image = new EntityImageTips(tips, bibliotekon);
			final EntityImageNote members = new EntityImageNote(named(diagram, "N9")) {
				@Override
				public XRectangle2D getInnerPosition(CharSequence member, StringBounder stringBounder) {
					if (member.toString().contains("start"))
						return new XRectangle2D(10, 20, 80, 14);
					if (member.toString().contains("priority"))
						return new XRectangle2D(10, 40, 90, 14);
					return null;
				}
			};
			bibliotekon.createNode(tips, image, BOUNDER).moveDelta(TIPS_CORNER.getX(), TIPS_CORNER.getY());
			bibliotekon.createNode(thread, members, BOUNDER).moveDelta(CLASS_CORNER.getX(), CLASS_CORNER.getY());
			dump("tips " + side, image);
		}
	}

	private void dump(String header, TextBlock block) throws Exception {
		out.println("=== " + header);
		final XDimension2D dim = block.calculateDimension(BOUNDER);
		out.println("dimension: " + dim.getWidth() + " " + dim.getHeight());
		final UGraphicDebug ug = new UGraphicDebug(1, dim, null, null, 0, "none");
		block.drawU(ug);
		final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
		ug.writeToStream(bytes, null, 96);
		final String[] lines = new String(bytes.toByteArray(), StandardCharsets.UTF_8).split("\n", -1);
		boolean inHeader = true;
		for (String line : lines) {
			if (inHeader) {
				inHeader = !line.isEmpty();
				continue;
			}
			out.println(line);
		}
	}
}
