import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import net.sourceforge.plantuml.SourceStringReader;
import net.sourceforge.plantuml.abel.Entity;
import net.sourceforge.plantuml.klimt.drawing.debug.UGraphicDebug;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;
import net.sourceforge.plantuml.statediagram.StateDiagram;
import net.sourceforge.plantuml.svek.Bibliotekon;
import net.sourceforge.plantuml.svek.GeneralImageBuilder;
import net.sourceforge.plantuml.svek.IEntityImage;

/**
 * Reads small state diagrams with PlantUML's own factory and draws the image of each leaf on the debug UGraphic,
 * for the exact comparison in crates/rockuml/src/diagram/state/image_tests.rs. The sources are written into the
 * fixture, so the Rust test reads the same diagrams.
 */
public class StateImageDump {

	private static final String[][] CASES = { //
			{ "plain", "[*] --> A", "A --> [*]", "A : first line", "A : second line", "state B",
					"state \"Long Name\\nOn Two Lines\" as C", "C : a //creole// **body**" }, //
			{ "pseudo", "state c <<choice>>", "state f <<fork>>", "state j <<join>>", "state h <<history>>",
					"state d <<history*>>", "state e <<end>>", "state s <<start>>", "X --> c", "Y --> [H]",
					"Z --> [H*]", "==bar== --> X", "W --> Z[H]", "W --> Z2[H*]" }, //
			{ "colors", "state Red #pink", "state Blue #lightblue ##[dashed]blue",
					"state Mixed #lightgray;line:red;line.dotted;text:red", "state Sym <<O-O>>",
					"state Bold ##[bold]green : body", "Red --> [*]" }, //
			{ "hide-empty", "hide empty description", "[*] --> Idle", "Idle --> Busy", "state Busy : working" }, //
			{ "skinparam", "skinparam state {", "  StartColor MediumBlue", "  EndColor Red",
					"  BackgroundColor Peru", "  BackgroundColor<<Warning>> Olive", "  BorderColor Gray",
					"  FontName Monospaced", "}", "[*] --> Idle", "state Idle <<Warning>>", "Idle --> [*]",
					"state Other : with a body" }, //
			{ "style", "<style>", "stateDiagram {", "  BackgroundColor Peru", "  FontColor Red", "  state {",
					"    name {", "      BackgroundColor LightBlue", "    }", "  }", "}", "</style>",
					"state A : described", "[*] --> A" }, //
			{ "border", "state S {", "  state e1 <<entryPoint>>", "  state x1 <<exitPoint>>",
					"  state i1 <<inputPin>>", "  state o1 <<outputPin>>", "  state ei <<expansionInput>>",
					"  state eo <<expansionOutput>>", "}" }, //
			{ "sdl", "state \"Req(Id)\" as ReqId <<sdlreceive>>", "state Plain <<sdlreceive>>",
					"state \"Two\\nLines\" as Two <<sdlreceive>>", "state Send <<sdlsend>>", "Plain --> ReqId" }, //
			{ "left-to-right", "left to right direction", "state f <<fork>>", "state S {",
					"  state ei <<expansionInput>>", "}", "f --> S" }, //
	};

	private final PrintStream out;
	private StringBounder bounder;

	private StateImageDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new StateImageDump(out).run();
		}
	}

	private void run() throws Exception {
		out.println("# Generated by tools/oracle/cuca-unit/state-images.sh from StateImageDump.java; do not edit.");
		bounder = new UGraphicDebug(1, new XDimension2D(0, 0), null, null, 0, "none").getStringBounder();
		for (String[] kase : CASES) {
			final StringBuilder source = new StringBuilder("@startuml\n");
			for (int i = 1; i < kase.length; i++)
				source.append(kase[i]).append("\n");
			source.append("@enduml\n");
			out.println("--- case " + kase[0]);
			out.print(source);
			final StateDiagram diagram = (StateDiagram) new SourceStringReader(source.toString()).getBlocks().get(0)
					.getDiagram();
			final Bibliotekon bibliotekon = new Bibliotekon(diagram.getLinks());
			for (Entity leaf : diagram.leafs()) {
				final IEntityImage image = GeneralImageBuilder.createEntityImageBlock(leaf,
						diagram.isHideEmptyDescriptionForState(), diagram, bibliotekon, null, diagram.getLinks());
				dump(kase[0] + " " + leaf.getUid() + " " + leaf.getName(), image);
			}
		}
	}

	private void dump(String header, IEntityImage image) throws Exception {
		out.println("=== " + header);
		final XDimension2D dim = image.calculateDimension(bounder);
		out.println("dimension: " + dim.getWidth() + " " + dim.getHeight());
		final UGraphicDebug ug = new UGraphicDebug(1, dim, null, null, 0, "none");
		image.drawU(ug);
		final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
		ug.writeToStream(bytes, null, 96);
		final String[] lines = new String(bytes.toByteArray(), StandardCharsets.UTF_8).split("\n", -1);
		boolean inHeader = true;
		for (String line : lines) {
			if (inHeader) {
				inHeader = !line.isEmpty();
				continue;
			}
			out.println(line);
		}
	}
}
