import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import gen.lib.pathplan.route__c;
import gen.lib.pathplan.shortest__c;
import gen.lib.pathplan.solvers__c;
import h.ST_Pedge_t;
import h.ST_Ppoly_t;
import h.ST_pointf;
import smetana.core.CArray;
import smetana.core.Globals;
import smetana.core.ZType;

/**
 * Dumps Smetana's path planner (gen/lib/pathplan) on generated inputs, for the bit-exact replay test in
 * crates/smetana/tests/pathplan.rs. Doubles are written as their 16 hex digit IEEE bits.
 *
 * Most cases route like routespl does: Pshortestpath through a polygon, then Proutespline along the shortest path
 * with the polygon's sides as barriers. All cases share one Globals, so the planner's scratch arrays carry over from
 * case to case as they do within a layout; a case that throws starts the next one on a fresh Globals.
 */
public class PathplanDump {
	private final Random random = new Random(20261007);
	private final PrintStream out;
	private Globals zz = Globals.open();

	private PathplanDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new PathplanDump(out).run();
		}
	}

	private void run() {
		out.println("# Generated by tools/oracle/smetana-unit/pathplan.sh from PathplanDump.java; do not edit.");
		for (int i = 0; i < 45; i++)
			corridor(i % 3 == 0);
		for (int i = 0; i < 25; i++)
			convex(3 + random.nextInt(10));
		for (int i = 0; i < 30; i++)
			star(4 + random.nextInt(14));
		for (int i = 0; i < 15; i++)
			collinear();
		for (int i = 0; i < 10; i++)
			duplicates();
		for (int i = 0; i < 15; i++)
			endpointsOnBoundary();
		for (int i = 0; i < 5; i++)
			destinationOutside();
		sourceOutside();
		for (int i = 0; i < 6; i++)
			bowTie();
		for (int i = 0; i < 12; i++)
			scrambled();
		for (int i = 0; i < 100; i++)
			spline();
		for (int i = 0; i < 100; i++)
			cubic();
	}

	// ---------------------------------------------------------------- generators

	/** Stacked boxes turned into a polygon the way routespl's _routesplines does for a downward edge. */
	private void corridor(boolean endpointsOnBoxSides) {
		final int boxn = 2 + random.nextInt(6);
		final double[] llx = new double[boxn], urx = new double[boxn], lly = new double[boxn], ury = new double[boxn];
		double y = random.nextInt(200);
		for (int i = 0; i < boxn; i++) {
			final double prevLeft = i == 0 ? random.nextInt(400) : llx[i - 1];
			final double prevRight = i == 0 ? prevLeft + 30 + random.nextInt(200) : urx[i - 1];
			// Neighbouring boxes overlap; sharing a side makes the polygon collinear or repeat points.
			llx[i] = random.nextInt(3) == 0 ? prevLeft : prevLeft + (random.nextInt(121) - 60) / 2.0;
			urx[i] = random.nextInt(3) == 0 ? prevRight : prevRight + (random.nextInt(121) - 60) / 2.0;
			if (urx[i] - llx[i] < 10)
				urx[i] = llx[i] + 10 + random.nextInt(40);
			if (llx[i] >= prevRight - 4 || urx[i] <= prevLeft + 4) {
				llx[i] = prevLeft;
				urx[i] = prevRight;
			}
			lly[i] = y;
			y += 8 + random.nextInt(60) + (random.nextBoolean() ? 0.5 : 0);
			ury[i] = y;
		}
		final List<double[]> poly = new ArrayList<>();
		for (int i = 0; i < boxn; i++) {
			poly.add(new double[] { urx[i], lly[i] });
			poly.add(new double[] { urx[i], ury[i] });
		}
		for (int i = boxn - 1; i >= 0; i--) {
			poly.add(new double[] { llx[i], ury[i] });
			poly.add(new double[] { llx[i], lly[i] });
		}
		final double[] start = { between(llx[0], urx[0]),
				endpointsOnBoxSides ? lly[0] : between(lly[0], ury[0]) };
		final double[] end = { between(llx[boxn - 1], urx[boxn - 1]),
				endpointsOnBoxSides ? ury[boxn - 1] : between(lly[boxn - 1], ury[boxn - 1]) };
		route("corridor", poly, start, end);
	}

	private void convex(int n) {
		final List<double[]> poly = ellipse(n);
		if (random.nextBoolean())
			java.util.Collections.reverse(poly);
		route("convex", poly, convexCombination(poly), convexCombination(poly));
	}

	/** A polygon around a centre with random radii; points inside a sector of the kernel are inside. */
	private void star(int n) {
		final double cx = random.nextInt(1000) - 500, cy = random.nextInt(1000) - 500;
		final double[] angles = sortedAngles(n);
		final List<double[]> poly = new ArrayList<>();
		final double radius = 20 + random.nextDouble() * 300;
		for (double a : angles) {
			final double r = radius * (0.25 + 0.75 * random.nextDouble());
			poly.add(new double[] { cx + r * Math.cos(a), cy + r * Math.sin(a) });
		}
		if (random.nextInt(4) == 0)
			java.util.Collections.reverse(poly);
		route("star", poly, inSector(cx, cy, poly), inSector(cx, cy, poly));
	}

	/** A convex polygon with extra points on its sides. */
	private void collinear() {
		final List<double[]> corners = ellipse(3 + random.nextInt(5));
		final List<double[]> poly = new ArrayList<>();
		for (int i = 0; i < corners.size(); i++) {
			final double[] a = corners.get(i), b = corners.get((i + 1) % corners.size());
			poly.add(a);
			for (int k = random.nextInt(3); k > 0; k--) {
				final double t = random.nextInt(3) == 0 ? 0.5 : random.nextDouble();
				poly.add(new double[] { a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1]) });
			}
		}
		route("collinear", poly, convexCombination(corners), convexCombination(corners));
	}

	/** Repeated consecutive points, which Pshortestpath skips. */
	private void duplicates() {
		final List<double[]> corners = ellipse(4 + random.nextInt(6));
		final List<double[]> poly = new ArrayList<>();
		for (double[] p : corners) {
			poly.add(p);
			if (random.nextInt(3) == 0)
				poly.add(p.clone());
		}
		route("duplicates", poly, convexCombination(corners), convexCombination(corners));
	}

	/** Endpoints on vertices or sides, or both endpoints the same. */
	private void endpointsOnBoundary() {
		final List<double[]> poly = rectilinear();
		final double[] vertex = poly.get(random.nextInt(poly.size())).clone();
		final int side = random.nextInt(poly.size());
		final double[] a = poly.get(side), b = poly.get((side + 1) % poly.size());
		final double t = random.nextInt(2) == 0 ? 0.5 : random.nextInt(4) / 4.0;
		final double[] onSide = { a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1]) };
		switch (random.nextInt(3)) {
		case 0:
			route("on-boundary", poly, vertex, onSide);
			break;
		case 1:
			route("on-boundary", poly, onSide, vertex);
			break;
		default:
			route("on-boundary", poly, onSide, onSide.clone());
		}
	}

	private void destinationOutside() {
		final List<double[]> poly = ellipse(3 + random.nextInt(8));
		route("destination-outside", poly, convexCombination(poly), new double[] { 5000, 5000 });
	}

	private void sourceOutside() {
		final List<double[]> poly = ellipse(5);
		route("source-outside", poly, new double[] { -5000, 5000 }, convexCombination(poly));
	}

	/** Self-intersecting polygons, on which triangulation can fail (Pshortestpath returns -2). */
	private void bowTie() {
		final double s = 10 + random.nextInt(100);
		final double x = random.nextInt(200), y = random.nextInt(200);
		final List<double[]> poly = new ArrayList<>();
		poly.add(new double[] { x, y });
		poly.add(new double[] { x + s, y + s });
		poly.add(new double[] { x + s, y });
		poly.add(new double[] { x, y + s });
		for (int k = random.nextInt(3); k > 0; k--)
			poly.add(new double[] { x - random.nextInt(50), y + random.nextInt((int) s) });
		route("bow-tie", poly, new double[] { x + s / 4, y + s / 2 }, new double[] { x + 3 * s / 4, y + s / 2 });
	}

	/** Random points in random order: mostly not simple polygons. */
	private void scrambled() {
		final int n = 4 + random.nextInt(7);
		final List<double[]> poly = new ArrayList<>();
		for (int i = 0; i < n; i++)
			poly.add(new double[] { random.nextInt(300), random.nextInt(300) });
		route("scrambled", poly, poly.get(0).clone(), poly.get(n / 2).clone());
	}

	/**
	 * Proutespline alone, on a wiggly polyline with end slopes: more inner points and smaller coordinates than
	 * shortest paths have, so that the spline fitting's rounding shows in its output. The barriers are none, the
	 * walls of a tube around the polyline, or scattered segments.
	 */
	private void spline() {
		final double unit = random.nextBoolean() ? 1 : 40;
		final int n = 3 + random.nextInt(10);
		final List<double[]> input = new ArrayList<>();
		double x = random.nextDouble() * 12 * unit, y = random.nextDouble() * 12 * unit;
		for (int i = 0; i < n; i++) {
			input.add(new double[] { x, y });
			x += (random.nextDouble() * 2 - 1) * unit;
			y += (0.3 + random.nextDouble()) * unit;
		}
		final List<double[]> barriers = new ArrayList<>();
		final String kind;
		switch (random.nextInt(3)) {
		case 0:
			kind = "free";
			break;
		case 1:
			kind = "tube";
			final double w = (0.3 + random.nextDouble() * 1.2) * unit;
			for (int i = 0; i + 1 < n; i++)
				for (double side : new double[] { -w, w })
					barriers.add(new double[] { input.get(i)[0] + side, input.get(i)[1], input.get(i + 1)[0] + side,
							input.get(i + 1)[1] });
			break;
		default:
			kind = "scattered";
			for (int k = 1 + random.nextInt(4); k > 0; k--) {
				final double[] p = input.get(random.nextInt(n));
				barriers.add(new double[] { p[0] + (random.nextDouble() * 4 - 2) * unit,
						p[1] + (random.nextDouble() * 4 - 2) * unit, p[0] + (random.nextDouble() * 4 - 2) * unit,
						p[1] + (random.nextDouble() * 4 - 2) * unit });
			}
		}
		final double a = random.nextDouble() * 2 * Math.PI, b = random.nextDouble() * 2 * Math.PI;
		final double[][] evs = random.nextBoolean()
				? new double[][] { { Math.cos(a), Math.sin(a) }, { -Math.cos(b), -Math.sin(b) } }
				: new double[][] { { random.nextDouble() * 4 - 2, random.nextDouble() * 4 - 2 },
						{ random.nextDouble() * 4 - 2, random.nextDouble() * 4 - 2 } };
		out.println("case spline-" + kind);
		out.println("input " + n + " " + hex(input));
		out.println("edges " + barriers.size() + " " + hex(barriers));
		out.println("evs " + hex(evs[0]) + " " + hex(evs[1]));

		final ST_Ppoly_t path = new ST_Ppoly_t();
		path.pn = n;
		path.ps = points(input);
		final CArray<ST_Pedge_t> edges = CArray.<ST_Pedge_t>ALLOC__(barriers.size(), ZType.ST_Pedge_t);
		for (int i = 0; i < barriers.size(); i++) {
			final double[] e = barriers.get(i);
			edges.get__(i).a.x = e[0];
			edges.get__(i).a.y = e[1];
			edges.get__(i).b.x = e[2];
			edges.get__(i).b.y = e[3];
		}
		proutespline(edges, barriers.size(), path, evs);
	}

	/** solve3 on the cubics splineintersectsline builds from a spline and a line. */
	private void cubic() {
		final double[] coeff = new double[4];
		final double[] v = new double[4];
		for (int i = 0; i < 4; i++)
			v[i] = random.nextInt(4) == 0 ? random.nextInt(400) : random.nextDouble() * 400;
		// points2coeff, then subtract the line's coordinate
		coeff[3] = v[3] + 3 * v[1] - (v[0] + 3 * v[2]);
		coeff[2] = 3 * v[0] + 3 * v[2] - 6 * v[1];
		coeff[1] = 3 * (v[1] - v[0]);
		coeff[0] = v[0] - between(-50, 450);
		final double[] roots = new double[3];
		final int rootn = solvers__c.solve3(coeff.clone(), roots);
		out.print("solve3 " + hex(coeff) + " => " + rootn);
		// 4 means "every t is a root"; the roots array is then left alone.
		for (int i = 0; rootn < 4 && i < rootn; i++)
			out.print(" " + hex(roots[i]));
		out.println();
	}

	// ---------------------------------------------------------------- the routing itself

	private void route(String label, List<double[]> polygon, double[] start, double[] end) {
		final double[][] evs = endVectors();
		out.println("case " + label);
		out.println("poly " + polygon.size() + " " + hex(polygon));
		out.println("eps " + hex(start) + " " + hex(end));
		out.println("evs " + hex(evs[0]) + " " + hex(evs[1]));

		final ST_Ppoly_t poly = new ST_Ppoly_t();
		poly.pn = polygon.size();
		poly.ps = points(polygon);
		final CArray<ST_pointf> eps = points(List.of(start, end));
		final ST_Ppoly_t path = new ST_Ppoly_t();
		final int rc;
		try {
			rc = shortest__c.Pshortestpath(zz, poly, eps, path);
		} catch (RuntimeException e) {
			out.println("shortest throws " + e.getClass().getSimpleName() + " " + e.getMessage());
			zz = Globals.open();
			return;
		}
		if (rc != 0) {
			out.println("shortest " + rc);
			return;
		}
		out.println("shortest 0 " + path.pn + " " + hex(path));

		final CArray<ST_Pedge_t> edges = CArray.<ST_Pedge_t>ALLOC__(poly.pn, ZType.ST_Pedge_t);
		for (int i = 0; i < poly.pn; i++) {
			edges.get__(i).a.___(poly.ps.get__(i));
			edges.get__(i).b.___(poly.ps.get__((i + 1) % poly.pn));
		}
		proutespline(edges, poly.pn, path, evs);
	}

	private void proutespline(CArray<ST_Pedge_t> edges, int edgen, ST_Ppoly_t path, double[][] evs) {
		final ST_Ppoly_t spline = new ST_Ppoly_t();
		try {
			final int rc = route__c.Proutespline(zz, edges, edgen, path, points(List.of(evs[0], evs[1])), spline);
			out.println("route " + rc + " " + spline.pn + " " + hex(spline));
		} catch (RuntimeException e) {
			out.println("route throws " + e.getClass().getSimpleName() + " " + e.getMessage());
			zz = Globals.open();
		}
	}

	/** End slopes as routespl sets them: none, cos/sin of a port angle, or arbitrary vectors that normv scales. */
	private double[][] endVectors() {
		switch (random.nextInt(4)) {
		case 0:
		case 1:
			return new double[][] { { 0, 0 }, { 0, 0 } };
		case 2:
			final double a = Math.PI / 2 * random.nextInt(4), b = random.nextDouble() * 2 * Math.PI;
			return new double[][] { { Math.cos(a), Math.sin(a) }, { -Math.cos(b), -Math.sin(b) } };
		default:
			return new double[][] { { random.nextDouble() * 4 - 2, random.nextDouble() * 4 - 2 },
					{ random.nextDouble() * 0.001, random.nextDouble() * 6 - 3 } };
		}
	}

	// ---------------------------------------------------------------- helpers

	private List<double[]> ellipse(int n) {
		final double cx = random.nextInt(1000) - 500, cy = random.nextInt(1000) - 500;
		final double rx = 10 + random.nextDouble() * 300, ry = 10 + random.nextDouble() * 300;
		final List<double[]> poly = new ArrayList<>();
		for (double a : sortedAngles(n))
			poly.add(new double[] { cx + rx * Math.cos(a), cy + ry * Math.sin(a) });
		return poly;
	}

	/** An axis-parallel polygon with integer corners, like the box corridors of real layouts. */
	private List<double[]> rectilinear() {
		final double x = random.nextInt(300), y = random.nextInt(300);
		final double w = 20 + random.nextInt(200), h = 20 + random.nextInt(100), notch = 5 + random.nextInt(15);
		final List<double[]> poly = new ArrayList<>();
		poly.add(new double[] { x, y });
		poly.add(new double[] { x + w, y });
		poly.add(new double[] { x + w, y + h });
		poly.add(new double[] { x + w - notch, y + h });
		poly.add(new double[] { x + w - notch, y + h + notch });
		poly.add(new double[] { x, y + h + notch });
		return poly;
	}

	private double[] sortedAngles(int n) {
		final double[] angles = new double[n];
		for (int i = 0; i < n; i++)
			angles[i] = random.nextDouble() * 2 * Math.PI;
		java.util.Arrays.sort(angles);
		return angles;
	}

	private double[] convexCombination(List<double[]> poly) {
		final double[] w = new double[poly.size()];
		double sum = 0;
		for (int i = 0; i < w.length; i++)
			sum += w[i] = random.nextInt(3) == 0 ? 0 : random.nextDouble();
		if (sum == 0) {
			w[0] = sum = 1;
		}
		double x = 0, y = 0;
		for (int i = 0; i < w.length; i++) {
			x += w[i] / sum * poly.get(i)[0];
			y += w[i] / sum * poly.get(i)[1];
		}
		return new double[] { x, y };
	}

	private double[] inSector(double cx, double cy, List<double[]> poly) {
		final int i = random.nextInt(poly.size());
		final double[] a = poly.get(i), b = poly.get((i + 1) % poly.size());
		final double s = random.nextDouble() * 0.9, t = random.nextDouble() * (0.9 - s);
		return new double[] { cx + s * (a[0] - cx) + t * (b[0] - cx), cy + s * (a[1] - cy) + t * (b[1] - cy) };
	}

	private double between(double lo, double hi) {
		return lo + random.nextDouble() * (hi - lo);
	}

	private static CArray<ST_pointf> points(List<double[]> list) {
		final CArray<ST_pointf> result = CArray.<ST_pointf>ALLOC__(list.size(), ZType.ST_pointf);
		for (int i = 0; i < list.size(); i++) {
			result.get__(i).x = list.get(i)[0];
			result.get__(i).y = list.get(i)[1];
		}
		return result;
	}

	private static String hex(double d) {
		return String.format("%016x", Double.doubleToRawLongBits(d));
	}

	private static String hex(double[] values) {
		final StringBuilder sb = new StringBuilder();
		for (double d : values)
			sb.append(sb.length() == 0 ? "" : " ").append(hex(d));
		return sb.toString();
	}

	private static String hex(List<double[]> points) {
		final StringBuilder sb = new StringBuilder();
		for (double[] p : points)
			sb.append(sb.length() == 0 ? "" : " ").append(hex(p));
		return sb.toString();
	}

	private static String hex(ST_Ppoly_t poly) {
		final List<double[]> points = new ArrayList<>();
		for (int i = 0; i < poly.pn; i++)
			points.add(new double[] { poly.ps.get__(i).x, poly.ps.get__(i).y });
		return hex(points);
	}
}
