import static gen.lib.cgraph.attr__c.agsafeset;
import static gen.lib.cgraph.edge__c.agedge;
import static gen.lib.cgraph.edge__c.agfstout;
import static gen.lib.cgraph.edge__c.agnxtout;
import static gen.lib.cgraph.graph__c.agnnodes;
import static gen.lib.cgraph.graph__c.agopen;
import static gen.lib.cgraph.node__c.agfstnode;
import static gen.lib.cgraph.node__c.agnode;
import static gen.lib.cgraph.node__c.agnxtnode;
import static gen.lib.cgraph.obj__c.agroot;
import static gen.lib.cgraph.rec__c.agbindrec;
import static gen.lib.cgraph.subg__c.agsubg;
import static gen.lib.common.input__c.graph_init;
import static gen.lib.common.postproc__c.dotneato_postprocess;
import static gen.lib.dotgen.dotinit__c.doDot;
import static gen.lib.gvc.gvc__c.gvContext;
import static gen.lib.gvc.gvlayout__c.gvlayout_select;
import static smetana.core.Macro.ED_edge_type;
import static smetana.core.Macro.ED_head_label;
import static smetana.core.Macro.ED_label;
import static smetana.core.Macro.ED_spl;
import static smetana.core.Macro.ED_tail_label;
import static smetana.core.Macro.ED_xlabel;
import static smetana.core.Macro.GD_bb;
import static smetana.core.Macro.GD_border;
import static smetana.core.Macro.GD_clust;
import static smetana.core.Macro.GD_drawing;
import static smetana.core.Macro.GD_flags;
import static smetana.core.Macro.GD_gvc;
import static smetana.core.Macro.GD_has_labels;
import static smetana.core.Macro.GD_label;
import static smetana.core.Macro.GD_label_pos;
import static smetana.core.Macro.GD_n_cluster;
import static smetana.core.Macro.GD_rankdir2;
import static smetana.core.Macro.LAYOUT_USES_RANKDIR;
import static smetana.core.Macro.ND_coord;
import static smetana.core.Macro.ND_height;
import static smetana.core.Macro.ND_ht;
import static smetana.core.Macro.ND_lw;
import static smetana.core.Macro.ND_rw;
import static smetana.core.Macro.ND_width;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import h.ST_Agedge_s;
import h.ST_Agnode_s;
import h.ST_Agobj_s;
import h.ST_Agraph_s;
import h.ST_GVC_s;
import h.ST_bezier;
import h.ST_boxf;
import h.ST_pointf;
import h.ST_splines;
import h.ST_textlabel_t;
import smetana.core.CString;
import smetana.core.Globals;
import smetana.core.ZType;
import smetana.core.size_t;

/**
 * Lays out the graph of every Smetana trace again and dumps the state that post-processing (dotneato_postprocess)
 * reads and the trace does not record, for crates/smetana/tests/postproc.rs. The test rebuilds the graph from the
 * trace's input section, fills it from the trace's "phase splines" section and this dump, post-processes it and
 * compares the result with the trace's "phase final" section.
 * <p>
 * Usage: PostprocDump tests/smetana out.txt. The dump only stands for the traced layout if the replay reproduces it,
 * so every trace's splines and final sections are checked against the replay; a mismatch aborts.
 */
public class PostprocDump {
	private final Globals zz = Globals.open();
	private ST_Agraph_s root;
	private ST_GVC_s gvc;
	private final Map<String, ST_Agraph_s> graphs = new HashMap<>();
	private final Map<String, ST_Agnode_s> nodes = new HashMap<>();
	private final List<ST_Agedge_s> edges = new ArrayList<>();

	public static void main(String[] args) throws IOException {
		final Path dir = Path.of(args[0]);
		final List<Path> traces;
		try (Stream<Path> walk = Files.walk(dir)) {
			traces = walk.filter(p -> p.toString().endsWith(".trace")).sorted().collect(Collectors.toList());
		}
		try (PrintStream out = new PrintStream(args[1], "UTF-8")) {
			out.println("# Generated by tools/oracle/smetana-unit/postproc.sh from PostprocDump.java; do not edit.");
			for (Path trace : traces) {
				out.println("trace " + dir.relativize(trace).toString().replace('\\', '/'));
				new PostprocDump().run(Files.readAllLines(trace, StandardCharsets.UTF_8), out);
			}
		}
	}

	private void run(List<String> trace, PrintStream out) {
		int line = 1;
		while (!trace.get(line).startsWith("gvLayoutJobs"))
			call(tokens(trace.get(line++)));
		agbindrec(zz, root, new CString("Agraphinfo_t"), new size_t(ZType.ST_Agraphinfo_t), true);
		GD_gvc(root, gvc);
		gvlayout_select(gvc, null);
		graph_init(zz, root, (gvc.layout.features.flags & LAYOUT_USES_RANKDIR) != 0);
		GD_drawing(agroot(root), GD_drawing(root));
		// dot_layout, split around post-processing.
		if (agnnodes(root) != 0)
			doDot(zz, root);
		final List<ST_Agnode_s> realNodes = new ArrayList<>();
		for (ST_Agnode_s n = agfstnode(zz, root); n != null; n = agnxtnode(zz, root, n))
			realNodes.add(n);
		edges.sort(Comparator.comparingInt(e -> e.tag.seq));

		check(trace, "splines", edgeLines());
		out.println("state State " + zz.State + " EdgeLabelsDone " + zz.EdgeLabelsDone);
		forEachGraph(root, g -> {
			final StringBuilder text = new StringBuilder("graph " + quote(name(g)) + " rankdir " + GD_rankdir2(g)
					+ " flags " + GD_flags(g) + " has_labels " + GD_has_labels(g) + " label_pos " + GD_label_pos(g)
					+ " bb " + box(GD_bb(g)) + " border");
			for (ST_pointf p : GD_border(g))
				text.append(' ').append(point(p));
			text.append(" clusters");
			for (int c = 1; c <= GD_n_cluster(g); c++)
				text.append(' ').append(quote(name(GD_clust(g).get_(c))));
			out.println(text);
			label(out::println, "graph " + quote(name(g)), "label", GD_label(g));
		});
		for (ST_Agnode_s n : realNodes)
			out.println("node " + quote(name(n)) + " coord " + point(ND_coord(n)) + " width " + number(ND_width(n))
					+ " height " + number(ND_height(n)) + " lw " + number(ND_lw(n)) + " rw " + number(ND_rw(n))
					+ " ht " + number(ND_ht(n)));
		for (ST_Agedge_s e : edges)
			if (ED_edge_type(e) != 0)
				out.println("edge e" + e.tag.seq + " edge_type " + ED_edge_type(e));

		dotneato_postprocess(zz, root);
		final List<String> fin = new ArrayList<>();
		forEachGraph(root, g -> {
			fin.add("graph " + quote(name(g)) + " bb " + box(GD_bb(g)));
			label(fin::add, "graph " + quote(name(g)), "label", GD_label(g));
		});
		for (ST_Agnode_s n : realNodes)
			fin.add("node " + quote(name(n)) + " coord " + point(ND_coord(n)) + " width " + number(ND_width(n))
					+ " height " + number(ND_height(n)) + " lw " + number(ND_lw(n)) + " rw " + number(ND_rw(n))
					+ " ht " + number(ND_ht(n)));
		fin.addAll(edgeLines());
		check(trace, "final", fin);
	}

	/** Fails unless the lines of the trace's phase section equal the replay's. */
	private static void check(List<String> trace, String phase, List<String> replayed) {
		final int start = trace.indexOf("phase " + phase) + 1;
		int end = start;
		while (end < trace.size() && !trace.get(end).startsWith("phase "))
			end++;
		if (start == 0 || !trace.subList(start, end).equals(replayed))
			throw new IllegalStateException("the replay differs from the trace in phase " + phase);
	}

	/** Splits a trace line as CgraphDump does. */
	private static List<String> tokens(String line) {
		final List<String> out = new ArrayList<>();
		int i = 0;
		while (i < line.length()) {
			final char c = line.charAt(i);
			if (c == ' ') {
				i++;
			} else if (c == '"') {
				final StringBuilder s = new StringBuilder();
				i++;
				while (line.charAt(i) != '"') {
					char d = line.charAt(i++);
					if (d == '\\') {
						d = line.charAt(i++);
						d = d == 'n' ? '\n' : d == 'r' ? '\r' : d == 't' ? '\t' : d;
					}
					s.append(d);
				}
				i++;
				out.add(s.toString());
			} else {
				int end = line.indexOf(' ', i);
				if (end < 0)
					end = line.length();
				String word = line.substring(i, end);
				if (word.startsWith("dim(") && word.endsWith(")")) {
					final String[] wh = word.substring(4, word.length() - 1).split(",");
					word = "_dim_" + wh[0] + "_" + wh[1] + "_";
				}
				out.add(word);
				i = end;
			}
		}
		return out;
	}

	private void call(List<String> t) {
		switch (t.get(0)) {
		case "agopen":
			root = agopen(zz, new CString(t.get(1)), zz.Agdirected, null);
			graphs.put(t.get(1), root);
			break;
		case "agsubg":
			graphs.put(t.get(3), agsubg(zz, graphs.get(t.get(2)), new CString(t.get(3)), true));
			break;
		case "agnode":
			nodes.put(t.get(3), agnode(zz, graphs.get(t.get(2)), new CString(t.get(3)), true));
			break;
		case "agedge":
			edges.add(agedge(zz, graphs.get(t.get(2)), nodes.get(t.get(4)), nodes.get(t.get(6)),
					t.size() > 7 ? new CString(t.get(7)) : null, true));
			break;
		case "agsafeset":
			agsafeset(zz, object(t.get(1), t.get(2)), new CString(t.get(3)), new CString(t.get(4)),
					new CString(t.get(5)));
			break;
		case "gvContext":
			gvc = gvContext(zz);
			break;
		default:
			throw new IllegalArgumentException(t.toString());
		}
	}

	private ST_Agobj_s object(String kind, String name) {
		switch (kind) {
		case "graph":
			return graphs.get(name);
		case "node":
			return nodes.get(name);
		default:
			return edges.get(Integer.parseInt(name.substring(1)) - 1);
		}
	}

	private String name(ST_Agobj_s obj) {
		return zz.all.get(obj.tag.id).getContent();
	}

	/** The edges' lines as the trace writes them. */
	private List<String> edgeLines() {
		final List<String> lines = new ArrayList<>();
		for (ST_Agedge_s e : edges) {
			final String ref = "edge e" + e.tag.seq;
			final ST_splines spl = ED_spl(e);
			if (spl == null)
				lines.add(ref + " spl none");
			else
				for (int i = 0; i < spl.size; i++)
					lines.add(ref + " bezier " + i + " " + bezier(spl.list.get__(i)));
			label(lines::add, ref, "label", ED_label(e));
			label(lines::add, ref, "head_label", ED_head_label(e));
			label(lines::add, ref, "tail_label", ED_tail_label(e));
			label(lines::add, ref, "xlabel", ED_xlabel(e));
		}
		return lines;
	}

	private static void label(Consumer<String> out, String ref, String kind, ST_textlabel_t label) {
		if (label != null)
			out.accept(ref + " " + kind + " pos " + point(label.pos) + " dimen " + point(label.dimen) + " set "
					+ label.set);
	}

	private static String bezier(ST_bezier bezier) {
		final StringBuilder text = new StringBuilder("sflag " + bezier.sflag + " eflag " + bezier.eflag + " sp "
				+ point(bezier.sp) + " ep " + point(bezier.ep) + " points " + bezier.size);
		for (int i = 0; i < bezier.size; i++)
			text.append(' ').append(point(bezier.list.get__(i)));
		return text.toString();
	}

	/** The graph, then its clusters depth-first in cluster-array order. */
	private static void forEachGraph(ST_Agraph_s g, Consumer<ST_Agraph_s> action) {
		action.accept(g);
		for (int c = 1; c <= GD_n_cluster(g); c++)
			forEachGraph(GD_clust(g).get_(c), action);
	}

	private static String number(double value) {
		return Double.toString(value);
	}

	private static String point(ST_pointf p) {
		return number(p.x) + " " + number(p.y);
	}

	private static String box(ST_boxf b) {
		return point(b.LL) + " " + point(b.UR);
	}

	private static String quote(String text) {
		final StringBuilder quoted = new StringBuilder("\"");
		for (char c : text.toCharArray()) {
			switch (c) {
			case '"':
				quoted.append("\\\"");
				break;
			case '\\':
				quoted.append("\\\\");
				break;
			case '\n':
				quoted.append("\\n");
				break;
			case '\r':
				quoted.append("\\r");
				break;
			case '\t':
				quoted.append("\\t");
				break;
			default:
				quoted.append(c);
			}
		}
		return quoted.append('"').toString();
	}
}
