package rockuml.oracle;

import static gen.lib.cgraph.attr__c.agsafeset;
import static gen.lib.cgraph.attr__c.agxget;
import static gen.lib.cgraph.edge__c.agedge;
import static gen.lib.cgraph.edge__c.aghead;
import static gen.lib.cgraph.graph__c.agopen;
import static gen.lib.cgraph.node__c.agnode;
import static gen.lib.gvc.gvc__c.gvContext;
import static gen.lib.gvc.gvlayout__c.gvLayoutJobs;
import static gen.lib.cgraph.edge__c.agtail;
import static gen.lib.cgraph.obj__c.agraphof;
import static smetana.core.Macro.AGMKOUT;
import static smetana.core.Macro.ED_edge_type;
import static smetana.core.Macro.ED_head_port;
import static smetana.core.Macro.ED_label;
import static smetana.core.Macro.ED_spl;
import static smetana.core.Macro.ED_tail_port;
import static smetana.core.Macro.ED_to_orig;
import static smetana.core.Macro.GD_bb;
import static smetana.core.Macro.GD_flags;
import static smetana.core.Macro.GD_rankdir2;
import static smetana.core.Macro.ND_coord;
import static smetana.core.Macro.ND_height;
import static smetana.core.Macro.ND_ht;
import static smetana.core.Macro.ND_in;
import static smetana.core.Macro.ND_lw;
import static smetana.core.Macro.ND_node_type;
import static smetana.core.Macro.ND_order;
import static smetana.core.Macro.ND_out;
import static smetana.core.Macro.ND_rank;
import static smetana.core.Macro.ND_rw;
import static smetana.core.Macro.ND_shape;
import static smetana.core.Macro.ND_shape_info;
import static smetana.core.Macro.ND_width;

import java.io.PrintStream;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Random;

import gen.lib.common.routespl__c;
import h.ST_Agedge_s;
import h.ST_Agnode_s;
import h.ST_Agobj_s;
import h.ST_Agraph_s;
import h.ST_Agsym_s;
import h.ST_Ppoly_t;
import h.ST_bezier;
import h.ST_boxf;
import h.ST_field_t;
import h.ST_path;
import h.ST_pathend_t;
import h.ST_pointf;
import h.ST_polygon_t;
import h.ST_port;
import h.ST_splineInfo;
import h.ST_splines;
import h.ST_textlabel_t;
import smetana.core.CArray;
import smetana.core.CArrayOfStar;
import smetana.core.CString;
import smetana.core.Globals;

/**
 * Records the calls Smetana's layouts make to the spline routing building blocks (splines.c, routespl.c and the
 * port functions of shapes.c) with their arguments, the state of the nodes and edges they read, and their results,
 * for the bit-exact replay test crates/smetana/tests/routing.rs. tools/oracle/smetana-unit/routing.sh compiles
 * copies of the three classes with calls to this one (routing-hooks.patch) and lays out graphs with them.
 *
 * <p>
 * Only outermost calls are recorded (the clip_and_install calls of makeSelfEdge are part of its result), and a
 * call is written only once it has returned. Before a call, the state of the objects it reads is written where it
 * differs from what the replay has: the state last written, updated by the effects of the calls themselves (the
 * {@code after} lines, which the replay compares). Doubles are Java's shortest round-trip decimals.
 */
public final class RoutingDump {
	private static PrintStream out;
	private static int depth;
	private static final Map<Globals, Layout> layouts = new IdentityHashMap<>();
	/** A random seed that times out ends the run: the default seeds never do. */
	private static final String RANDOM_TIMEOUT_SECONDS = "120";
	private static Layout lastLayout;

	private RoutingDump() {
	}

	/**
	 * args: fixture, then {@code random <trace dir> <seed or first-last>...}, {@code synthetic <count>} or
	 * {@code corpus <files...>}.
	 */
	public static void main(String[] args) throws Exception {
		try (PrintStream ps = new PrintStream(args[0], "UTF-8")) {
			out = ps;
			out.println("# Generated by tools/oracle/smetana-unit/routing.sh from RoutingDump.java; do not edit.");
			if (args[1].equals("random")) {
				final List<String> randomArgs = new ArrayList<>(List.of(args[2], RANDOM_TIMEOUT_SECONDS));
				for (int i = 3; i < args.length; i++) {
					final String[] range = args[i].split("-");
					final int last = Integer.parseInt(range[range.length - 1]);
					for (int seed = Integer.parseInt(range[0]); seed <= last; seed++)
						randomArgs.add(Integer.toString(seed));
				}
				RandomGraphs.main(randomArgs.toArray(new String[0]));
			} else if (args[1].equals("synthetic")) {
				final int count = Integer.parseInt(args[2]);
				for (int seed = 1; seed <= count; seed++) {
					arrows(new Random(seed));
					corridors(new Random(seed));
				}
			} else {
				final List<String> plantuml = new ArrayList<>();
				plantuml.add("-f");
				plantuml.add("debug");
				// One thread: the recorder is not thread-safe, and layouts must not interleave.
				plantuml.add("-nbthread");
				plantuml.add("1");
				plantuml.add("-o");
				plantuml.add(Files.createTempDirectory("routing").toString());
				for (int i = 2; i < args.length; i++)
					plantuml.add(args[i]);
				// Run.main exits the JVM, which closes nothing: write as we go.
				out = new PrintStream(ps, true, "UTF-8");
				net.sourceforge.plantuml.Run.main(plantuml.toArray(new String[0]));
			}
		}
	}

	// ---------------------------------------------------------------- synthetic inputs

	/**
	 * A small graph with arrows PlantUML does not draw (arrowtail normal, large arrowsize), self loops, back and
	 * multi-edges, sometimes left to right.
	 */
	private static void arrows(Random random) {
		final Globals zz = Globals.open();
		try {
			final ST_Agraph_s g = agopen(zz, new CString("g"), zz.Agdirected, null);
			if (random.nextInt(4) == 0)
				set(zz, g, "rankdir", "LR");
			final int n = 2 + random.nextInt(6);
			final List<ST_Agnode_s> nodes = new ArrayList<>();
			for (int i = 0; i < n; i++) {
				final ST_Agnode_s node = agnode(zz, g, new CString("N" + i), true);
				set(zz, node, "shape", "box");
				set(zz, node, "width", "" + (20 + random.nextInt(100)) / 72.0);
				set(zz, node, "height", "" + (20 + random.nextInt(40)) / 72.0);
				nodes.add(node);
			}
			final String[] arrows = { "none", "normal" };
			final String[] sizes = { ".7", "1", "2", "4" };
			for (int k = n + random.nextInt(n); k > 0; k--) {
				final ST_Agnode_s a = nodes.get(random.nextInt(n));
				final ST_Agnode_s b = nodes.get(random.nextInt(n));
				final ST_Agobj_s e = agedge(zz, g, a, b, null, true);
				set(zz, e, "arrowsize", sizes[random.nextInt(sizes.length)]);
				set(zz, e, "arrowtail", arrows[random.nextInt(2)]);
				set(zz, e, "arrowhead", arrows[random.nextInt(2)]);
			}
			gvLayoutJobs(zz, gvContext(zz), g);
		} catch (RuntimeException e) {
			// Smetana gave up on this graph; the calls it made before stay recorded.
		} finally {
			Globals.close();
		}
	}

	/**
	 * routesplines on box corridors that checkpath has to repair: boxes apart in x or y or both, overlapping, or
	 * degenerate. The path's edge comes from a laid out two-node graph.
	 */
	private static void corridors(Random random) {
		final Globals zz = Globals.open();
		try {
			final ST_Agraph_s g = agopen(zz, new CString("g"), zz.Agdirected, null);
			final ST_Agnode_s a = agnode(zz, g, new CString("a"), true);
			final ST_Agnode_s b = agnode(zz, g, new CString("b"), true);
			set(zz, a, "shape", "box");
			set(zz, b, "shape", "box");
			final ST_Agedge_s e = (ST_Agedge_s) agedge(zz, g, a, b, null, true);
			gvLayoutJobs(zz, gvContext(zz), g);
			for (int template = 0; template < CORRIDORS.length; template++)
				corridor(zz, e, CORRIDORS[template], random);
		} catch (RuntimeException e) {
			// As above.
		} finally {
			Globals.close();
		}
	}

	/** Three or four boxes each (LLx, LLy, URx, URy), from the tail's end to the head's. */
	private static final double[][][] CORRIDORS = {
			{ { 0, 60, 40, 80 }, { 60, 40, 120, 60 }, { 60, 20, 120, 40 } }, // apart, left of the next
			{ { 80, 60, 120, 80 }, { 0, 40, 60, 60 }, { 0, 20, 60, 40 } }, // apart, right of the next
			{ { 0, 0, 100, 20 }, { 0, 30, 100, 50 }, { 0, 50, 100, 70 } }, // upwards, apart below the next
			{ { 0, 60, 100, 80 }, { 0, 30, 100, 50 }, { 0, 10, 100, 30 } }, // apart above the next
			{ { 80, 60, 120, 80 }, { 0, 30, 60, 50 }, { 0, 10, 60, 30 } }, // apart on both axes
			{ { 0, 40, 40, 60 }, { 30, 10, 140, 55 }, { 30, 0, 140, 10 } }, // overlapping, x less
			{ { 0, 30, 100, 80 }, { 0, 20, 100, 40 }, { 0, 0, 100, 20 } }, // overlapping, y less
			{ { 0, 60, 100, 80 }, { 0, 59.995, 100, 60 }, { 0, 40, 100, 60 }, { 0, 20, 100, 40 } }, // degenerate
	};

	private static void corridor(Globals zz, ST_Agedge_s e, double[][] template, Random random) {
		final double sx = random.nextInt(200) + (random.nextBoolean() ? 0.5 : 0);
		final double sy = random.nextInt(200) + (random.nextBoolean() ? 0.5 : 0);
		final ST_path P = new ST_path();
		P.nbox = template.length;
		P.boxes = new ST_boxf[template.length];
		for (int i = 0; i < template.length; i++) {
			P.boxes[i] = new ST_boxf();
			P.boxes[i].LL.x = template[i][0] + sx;
			P.boxes[i].LL.y = template[i][1] + sy;
			P.boxes[i].UR.x = template[i][2] + sx;
			P.boxes[i].UR.y = template[i][3] + sy;
		}
		final ST_boxf first = P.boxes[0], last = P.boxes[template.length - 1];
		final boolean down = first.LL.y > last.LL.y;
		P.start.p.x = first.LL.x + random.nextDouble() * (first.UR.x - first.LL.x);
		P.start.p.y = down ? first.UR.y - 1 : first.LL.y + 1;
		P.end.p.x = last.LL.x + random.nextDouble() * (last.UR.x - last.LL.x);
		P.end.p.y = down ? last.LL.y + 1 : last.UR.y - 1;
		if (random.nextInt(4) == 0)
			P.end.p.x += random.nextBoolean() ? 300 : -300; // outside: checkpath moves it in
		P.start.constrained = random.nextBoolean();
		P.start.theta = -Math.PI / 2;
		P.end.constrained = random.nextBoolean();
		P.end.theta = Math.PI / 2;
		P.data = e;
		try {
			if (random.nextInt(4) == 0)
				routespl__c.routepolylines(zz, P, new int[1]);
			else
				routespl__c.routesplines(zz, P, new int[1]);
		} catch (RuntimeException ex) {
			// Smetana rejects the corridor; nothing is recorded.
		}
	}

	private static void set(Globals zz, ST_Agobj_s object, String name, String value) {
		agsafeset(zz, object, new CString(name), new CString(value), new CString(""));
	}

	// ---------------------------------------------------------------- hooks

	public static Event clip_and_install(Globals zz, ST_Agedge_s fe, ST_Agnode_s hn, CArray<ST_pointf> ps, int pn,
			ST_splineInfo info) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		involve(ev, fe);
		involve(ev, hn);
		writeState(ev);
		ev.line("clip_and_install fe " + edge(ev, fe) + " hn " + node(ev, hn) + info(info) + " ps "
				+ points(ps, pn));
		ev.args = new Object[] { fe, ps, pn };
		return ev;
	}

	public static void clip_and_install_done(Event ev) {
		if (ev == null)
			return;
		ev.line("=> ps " + points((CArray<ST_pointf>) ev.args[1], (Integer) ev.args[2]));
		ev.line("=> " + bezier(lastBezier((ST_Agedge_s) ev.args[0])));
		write(ev);
	}

	public static Event beginpath(Globals zz, ST_path P, ST_Agedge_s e, int et, ST_pathend_t endp, boolean merge,
			boolean begin) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		involve(ev, e);
		writeState(ev);
		ev.line((begin ? "beginpath" : "endpath") + " e " + edge(ev, e) + " et " + et + " merge " + b(merge)
				+ " endp " + endp(endp));
		ev.args = new Object[] { P, endp, begin };
		return ev;
	}

	public static void beginpath_done(Event ev) {
		if (ev == null)
			return;
		final ST_path P = (ST_path) ev.args[0];
		final ST_port p = (Boolean) ev.args[2] ? P.start : P.end;
		ev.line("=> port " + pt(p.p) + " " + d(p.theta) + " " + b(p.constrained) + " nbox " + P.nbox + " endp "
				+ endp((ST_pathend_t) ev.args[1]));
		write(ev);
	}

	public static Event routesplines(Globals zz, ST_path pp, int polyline) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		involve(ev, pp.data);
		writeState(ev);
		ev.line("routesplines e " + edge(ev, pp.data) + " polyline " + polyline + " start " + pathPort(pp.start)
				+ " end " + pathPort(pp.end) + " boxes " + boxes(pp));
		ev.args = new Object[] { pp };
		return ev;
	}

	public static void routesplines_done(Event ev, CArray<ST_pointf> ps, int pn) {
		if (ev == null)
			return;
		final ST_path pp = (ST_path) ev.args[0];
		ev.line("=> " + (ps == null ? "null" : "points " + points(ps, pn)));
		ev.line("=> start " + pt(pp.start.p) + " end " + pt(pp.end.p) + " boxes " + boxes(pp));
		write(ev);
	}

	public static Event simpleSplineRoute(Globals zz, ST_pointf tp, ST_pointf hp, ST_Ppoly_t poly, boolean polyline) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		ev.line("simpleSplineRoute tp " + pt(tp) + " hp " + pt(hp) + " polyline " + b(polyline) + " poly "
				+ points(poly.ps, poly.pn));
		return ev;
	}

	public static void simpleSplineRoute_done(Event ev, CArray<ST_pointf> ps, int pn) {
		if (ev == null)
			return;
		ev.line("=> " + (ps == null ? "null" : "points " + points(ps, pn)));
		write(ev);
	}

	public static Event makeSelfEdge(Globals zz, CArrayOfStar<ST_Agedge_s> edges, int ind, int cnt, double sizex,
			double sizey, ST_splineInfo sinfo) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		final ST_Agedge_s[] loops = new ST_Agedge_s[cnt];
		for (int i = 0; i < cnt; i++) {
			loops[i] = edges.get_(ind + i);
			involve(ev, loops[i]);
		}
		writeState(ev);
		final StringBuilder sb = new StringBuilder("makeSelfEdge sizex " + d(sizex) + " sizey " + d(sizey)
				+ info(sinfo) + " edges " + cnt);
		for (ST_Agedge_s e : loops)
			sb.append(' ').append(edge(ev, e));
		ev.line(sb.toString());
		ev.args = loops;
		return ev;
	}

	public static void makeSelfEdge_done(Event ev) {
		if (ev == null)
			return;
		for (Object e : ev.args)
			ev.line("=> " + bezier(lastBezier((ST_Agedge_s) e)));
		write(ev);
	}

	public static Event port(Globals zz, ST_Agnode_s n, CString portname, CString compass, String fn) {
		final Event ev = enter(zz);
		if (ev == null)
			return null;
		involve(ev, n);
		writeState(ev);
		ev.line(fn + " n " + node(ev, n) + " name " + quote(portname.getContent()) + " compass "
				+ (compass == null ? "-" : quote(compass.getContent())));
		return ev;
	}

	public static void port_done(Event ev, ST_port p) {
		if (ev == null)
			return;
		ev.line("=> port " + port(p));
		write(ev);
	}

	public static void leave(Event ev) {
		depth--;
	}

	// ---------------------------------------------------------------- per layout identities and known state

	private static final class Layout {
		final int index;
		final Map<Object, Integer> nodes = new IdentityHashMap<>();
		final Map<Object, Integer> edges = new IdentityHashMap<>();
		final Map<String, String> known = new HashMap<>();

		Layout(int index) {
			this.index = index;
		}
	}

	/** One recorded call: its lines, and the state the replay will have once it is written. */
	public static final class Event {
		final Globals zz;
		final Layout layout;
		final StringBuilder text = new StringBuilder();
		final Map<String, String> known = new HashMap<>();
		final LinkedHashSet<ST_Agnode_s> nodes = new LinkedHashSet<>();
		final LinkedHashSet<ST_Agedge_s> edges = new LinkedHashSet<>();
		ST_Agraph_s graph;
		Object[] args;

		Event(Globals zz, Layout layout) {
			this.zz = zz;
			this.layout = layout;
		}

		void line(String s) {
			text.append(s).append('\n');
		}
	}

	private static Event enter(Globals zz) {
		depth++;
		if (out == null || depth != 1)
			return null;
		Layout layout = layouts.get(zz);
		if (layout == null) {
			layout = new Layout(layouts.size());
			layouts.put(zz, layout);
		}
		final Event ev = new Event(zz, layout);
		if (layout != lastLayout)
			ev.line("layout " + layout.index);
		if (!layout.known.containsKey("syms"))
			state(ev, "syms" + sym(" dir", zz.E_dir) + sym(" arrowhead", zz.E_arrowhead)
					+ sym(" arrowtail", zz.E_arrowtail) + sym(" arrowsize", zz.E_arrowsz));
		return ev;
	}

	/** Adds an edge, the edges it stands for (ED_to_orig) and all their end nodes to the event's objects. */
	private static void involve(Event ev, ST_Agedge_s e) {
		for (; e != null; e = ED_to_orig(e)) {
			ev.edges.add(AGMKOUT(e));
			involve(ev, agtail(e));
			involve(ev, aghead(e));
		}
	}

	private static void involve(Event ev, ST_Agnode_s n) {
		ev.nodes.add(n);
		ev.graph = agraphof(n);
	}

	private static int node(Event ev, ST_Agnode_s n) {
		return ev.layout.nodes.computeIfAbsent(n, k -> ev.layout.nodes.size());
	}

	private static int edge(Event ev, ST_Agedge_s e) {
		return ev.layout.edges.computeIfAbsent(AGMKOUT(e), k -> ev.layout.edges.size());
	}

	/** Writes the state lines of the event's objects that the replay does not have. */
	private static void writeState(Event ev) {
		for (ST_Agnode_s n : ev.nodes)
			node(ev, n);
		for (ST_Agedge_s e : ev.edges)
			edge(ev, e);
		if (ev.graph != null)
			state(ev, graphState(ev.graph));
		for (ST_Agnode_s n : ev.nodes) {
			state(ev, shapeInfo(ev, n));
			state(ev, nodeState(ev, n));
		}
		for (ST_Agedge_s e : ev.edges)
			state(ev, edgeState(ev, e));
	}

	private static void state(Event ev, String s) {
		final String key = key(s);
		if (!s.equals(ev.layout.known.get(key)))
			ev.line(s);
		ev.known.put(key, s);
	}

	/** Writes the event's objects' state after the call where it changed; the replay compares these. */
	private static void writeStateAfter(Event ev) {
		if (ev.graph != null)
			after(ev, graphState(ev.graph));
		for (ST_Agnode_s n : ev.nodes)
			after(ev, nodeState(ev, n));
		for (ST_Agedge_s e : ev.edges)
			after(ev, edgeState(ev, e));
	}

	private static void after(Event ev, String s) {
		final String key = key(s);
		if (!s.equals(ev.known.get(key)))
			ev.line("after " + s);
		ev.known.put(key, s);
	}

	private static String key(String stateLine) {
		final String[] t = stateLine.split(" ", 3);
		return t[0].equals("graph") || t[0].equals("syms") ? t[0] : t[0] + " " + t[1];
	}

	private static void write(Event ev) {
		writeStateAfter(ev);
		out.print(ev.text);
		out.println("end");
		ev.layout.known.putAll(ev.known);
		lastLayout = ev.layout;
	}

	// ---------------------------------------------------------------- state

	private static String graphState(ST_Agraph_s g) {
		return "graph rankdir " + GD_rankdir2(g) + " flags " + GD_flags(g) + " bb " + box(GD_bb(g));
	}

	private static String nodeState(Event ev, ST_Agnode_s n) {
		return "node " + node(ev, n) + " type " + ND_node_type(n) + " rank " + ND_rank(n) + " order "
				+ ND_order(n) + " coord " + pt(ND_coord(n)) + " lw " + d(ND_lw(n)) + " rw " + d(ND_rw(n)) + " ht "
				+ d(ND_ht(n)) + " width " + d(ND_width(n)) + " height " + d(ND_height(n)) + " in " + ND_in(n).size
				+ " out " + ND_out(n).size;
	}

	/** The node's shape and its polygon or record fields, which do not change once nodes are sized. */
	private static String shapeInfo(Event ev, ST_Agnode_s n) {
		final String prefix = "shape " + node(ev, n) + " ";
		if (ND_shape(n) == null)
			return prefix + "-";
		final String name = ND_shape(n).name.getContent();
		final Object info = ND_shape_info(n);
		if (info instanceof ST_polygon_t) {
			final ST_polygon_t poly = (ST_polygon_t) info;
			final int count = poly.sides * Math.max(poly.peripheries, 1);
			final StringBuilder sb = new StringBuilder(prefix + name + " poly " + poly.sides + " " + poly.peripheries
					+ " " + poly.option + " " + count);
			for (int i = 0; i < count; i++)
				sb.append(' ').append(pt(poly.vertices.get__(i)));
			return sb.toString();
		}
		final StringBuilder sb = new StringBuilder(prefix + name + " record");
		field(sb, (ST_field_t) info);
		return sb.toString();
	}

	/** A field and its subfields, depth first: {@code LLx LLy URx URy sides id|- n_flds}. */
	private static void field(StringBuilder sb, ST_field_t f) {
		sb.append(' ').append(box(f.b)).append(' ').append(f.sides).append(' ')
				.append(f.id == null ? "-" : quote(f.id.getContent())).append(' ').append(f.n_flds);
		for (int i = 0; i < f.n_flds; i++)
			field(sb, f.fld.get_(i));
	}

	private static String edgeState(Event ev, ST_Agedge_s e) {
		final ST_textlabel_t l = ED_label(e);
		final ST_splines spl = ED_spl(e);
		final ST_Agedge_s orig = ED_to_orig(e);
		String s = "edge " + edge(ev, e) + " tail " + node(ev, agtail(e)) + " head " + node(ev, aghead(e))
				+ " type " + ED_edge_type(e) + " orig " + (orig == null ? "-" : "" + edge(ev, orig)) + " tport "
				+ port(ED_tail_port(e)) + " hport " + port(ED_head_port(e)) + " label "
				+ (l == null ? "-" : pt(l.dimen) + " " + pt(l.pos) + " " + l.set) + " spl "
				+ (spl == null ? "-" : "" + spl.size);
		if (orig == null) {
			final Globals zz = ev.zz;
			s += " attrs" + attr(e, zz.E_dir) + attr(e, zz.E_arrowhead) + attr(e, zz.E_arrowtail)
					+ attr(e, zz.E_arrowsz);
		}
		return s;
	}

	private static String attr(ST_Agedge_s e, ST_Agsym_s sym) {
		return " " + (sym == null ? "-" : quote(agxget(e, sym).getContent()));
	}

	/** All of a port but its name, which nothing here reads. */
	private static String port(ST_port p) {
		return pt(p.p) + " " + d(p.theta) + " " + (p.bp == null ? "-" : box(p.bp)) + " " + b(p.defined) + " "
				+ b(p.constrained) + " " + b(p.clip) + " " + b(p.dyna) + " " + p.order + " " + p.side;
	}

	private static String pathPort(ST_port p) {
		return pt(p.p) + " " + d(p.theta) + " " + b(p.constrained);
	}

	private static String endp(ST_pathend_t endp) {
		return box(endp.nb) + " " + pt(endp.np) + " " + endp.sidemask + " " + endp.boxn[0] + " "
				+ box(endp.boxes[0]);
	}

	private static String boxes(ST_path pp) {
		final StringBuilder sb = new StringBuilder("" + pp.nbox);
		for (int i = 0; i < pp.nbox; i++)
			sb.append(' ').append(box(pp.boxes[i]));
		return sb.toString();
	}

	private static String sym(String name, ST_Agsym_s sym) {
		return name + " " + (sym == null ? 0 : 1);
	}

	private static String info(ST_splineInfo info) {
		return " ignoreSwap " + b(info.ignoreSwap) + " isOrtho " + b(info.isOrtho);
	}

	private static String bezier(ST_bezier bz) {
		return "bezier " + bz.sflag + " " + bz.eflag + " " + pt(bz.sp) + " " + pt(bz.ep) + " "
				+ points(bz.list, bz.size);
	}

	/** The Bézier a call just appended to the splines of e's real edge. */
	private static ST_bezier lastBezier(ST_Agedge_s e) {
		while (ED_edge_type(e) != 0)
			e = ED_to_orig(e);
		final ST_splines spl = ED_spl(e);
		return spl.list.get__(spl.size - 1);
	}

	private static String points(CArray<ST_pointf> ps, int n) {
		final StringBuilder sb = new StringBuilder("" + n);
		for (int i = 0; i < n; i++)
			sb.append(' ').append(pt(ps.get__(i)));
		return sb.toString();
	}

	private static String b(boolean v) {
		return v ? "1" : "0";
	}

	private static String d(double v) {
		return Double.toString(v);
	}

	private static String pt(ST_pointf p) {
		return d(p.x) + " " + d(p.y);
	}

	private static String box(ST_boxf b) {
		return pt(b.LL) + " " + pt(b.UR);
	}

	private static String quote(String s) {
		return '"' + s.replace("\\", "\\\\").replace("\"", "\\\"").replace(" ", "\\s") + '"';
	}
}
