import java.io.PrintStream;
import java.util.IdentityHashMap;
import java.util.Map;
import java.util.Random;

import gen.lib.label.index__c;
import gen.lib.label.xlabels__c;
import h.ST_LeafList_t;
import h.ST_Node_t___;
import h.ST_RTree;
import h.ST_Rect_t;
import h.ST_label_params_t;
import h.ST_object_t;
import h.ST_point;
import h.ST_xlabel_t;
import smetana.core.CArray;
import smetana.core.Globals;
import smetana.core.ZType;

/**
 * Dumps Smetana's external label placer (gen/lib/label) on generated inputs, for the bit-exact replay test in
 * crates/smetana/tests/xlabels.rs: Hilbert keys, R-tree searches, and whole placeLabels runs on scenes shaped like
 * the ones addXLabels builds. Doubles are written as their 16 hex digit IEEE bits.
 */
public class XlabelsDump {
	private final Random random = new Random(20261008);
	private final PrintStream out;

	private XlabelsDump(PrintStream out) {
		this.out = out;
	}

	public static void main(String[] args) throws Exception {
		try (PrintStream out = new PrintStream(args[0], "UTF-8")) {
			new XlabelsDump(out).run();
		}
	}

	private void run() {
		out.println("# Generated by tools/oracle/smetana-unit/xlabels.sh from XlabelsDump.java; do not edit.");
		for (int i = 0; i < 400; i++)
			hilbert();
		for (int i = 0; i < 40; i++)
			rtree(1 + random.nextInt(i < 20 ? 70 : 600), false);
		for (int i = 0; i < 4; i++)
			rtree(60 + random.nextInt(100), true);
		for (int i = 0; i < 150; i++)
			place(i);
	}

	private static String hex(double d) {
		return String.format("%016x", Double.doubleToRawLongBits(d));
	}

	// ---------------------------------------------------------------- Hilbert keys

	private void hilbert() {
		final ST_point p = new ST_point();
		final int kind = random.nextInt(4);
		if (kind == 0) {
			p.x = random.nextInt();
			p.y = random.nextInt();
		} else if (kind == 1) {
			p.x = random.nextInt(4001) - 2000;
			p.y = random.nextInt(4001) - 2000;
		} else {
			p.x = random.nextInt(5000);
			p.y = random.nextInt(5000);
		}
		final int n = random.nextInt(33);
		out.println("hilbert " + p.x + " " + p.y + " " + n + " " + xlabels__c.hd_hil_s_from_xy(p, n));
	}

	// ---------------------------------------------------------------- R-tree

	private ST_Rect_t rect(int maxCoord, int maxSize) {
		final ST_Rect_t r = new ST_Rect_t();
		r.boundary[0] = random.nextInt(maxCoord) - maxCoord / 4;
		r.boundary[1] = random.nextInt(maxCoord) - maxCoord / 4;
		r.boundary[2] = r.boundary[0] + 1 + random.nextInt(maxSize);
		r.boundary[3] = r.boundary[1] + 1 + random.nextInt(maxSize);
		return r;
	}

	private static String rect(ST_Rect_t r) {
		return r.boundary[0] + " " + r.boundary[1] + " " + r.boundary[2] + " " + r.boundary[3];
	}

	/**
	 * Inserts n rectangles at level 0, as xlspdxload does, then searches. With identical rectangles every split
	 * finds no waste and PickSeeds puts branch 0 in both groups, which drops a branch.
	 */
	private void rtree(int n, boolean identical) {
		out.println("rtree " + n);
		final ST_RTree tree = index__c.RTreeOpen();
		final Map<ST_object_t, Integer> ids = new IdentityHashMap<>();
		final ST_Rect_t same = rect(1000, 50);
		for (int i = 0; i < n; i++) {
			final ST_Rect_t r = identical ? same : rect(2000, 1 + random.nextInt(3) * 100);
			final ST_object_t data = new ST_object_t();
			ids.put(data, i);
			out.println("insert " + rect(r));
			final ST_Node_t___[] root = new ST_Node_t___[] { tree.root };
			index__c.RTreeInsert(tree, r, data, root, 0);
			tree.root = root[0];
		}
		for (int i = 0; i < 25; i++) {
			final ST_Rect_t q = identical && i == 0 ? same : rect(2000, 1 + random.nextInt(800));
			final StringBuilder line = new StringBuilder("search " + rect(q) + " ->");
			for (ST_LeafList_t l = index__c.RTreeSearch(tree, tree.root, q); l != null; l = l.next)
				line.append(' ').append(ids.get((ST_object_t) l.leaf.child));
			out.println(line);
		}
	}

	// ---------------------------------------------------------------- placeLabels

	/** A scene like addXLabels': nodes, placed edge labels, and head/tail labels at spline ends to place. */
	private void place(int index) {
		final int nodes = 1 + random.nextInt(index < 50 ? 8 : index < 120 ? 40 : 90);
		final int placed = random.nextInt(1 + nodes / 3);
		final int labels = 1 + random.nextInt(1 + nodes);
		final int n_objs = nodes + placed + labels;
		final CArray<ST_object_t> objs = CArray.<ST_object_t>ALLOC__(n_objs, ZType.ST_object_t);
		final CArray<ST_xlabel_t> lbls = CArray.<ST_xlabel_t>ALLOC__(labels, ZType.ST_xlabel_t);
		final double xoff = random.nextInt(3) == 0 ? -random.nextInt(400) - 0.5 : 0;
		final double[][] centers = new double[nodes][];
		final double[][] sizes = new double[nodes][];
		int o = 0;
		int l = 0;
		for (int i = 0; i < nodes; i++) {
			final ST_object_t obj = objs.get__(o++);
			final double w = 20 + random.nextInt(180);
			final double h = 20 + random.nextInt(80);
			final double cx = xoff + random.nextInt(1200) + (random.nextBoolean() ? 0.5 : 0);
			final double cy = 30 + 90 * random.nextInt(1 + nodes / 4) + random.nextInt(20);
			centers[i] = new double[] { cx, cy };
			sizes[i] = new double[] { w, h };
			obj.sz.x = w;
			obj.sz.y = h;
			obj.pos.x = cx - w / 2.0;
			obj.pos.y = cy - h / 2.0;
		}
		for (int i = 0; i < placed; i++) {
			final ST_object_t obj = objs.get__(o++);
			obj.sz.x = 10 + random.nextInt(120);
			obj.sz.y = 15 + random.nextInt(18);
			obj.pos.x = xoff + random.nextInt(1200) + random.nextDouble() - obj.sz.x / 2.0;
			obj.pos.y = random.nextInt(90 * (1 + nodes / 4)) + random.nextDouble() - obj.sz.y / 2.0;
		}
		double[] previous = null;
		for (int i = 0; i < labels; i++) {
			final ST_object_t obj = objs.get__(o++);
			final ST_xlabel_t xl = lbls.get__(l);
			final int k = random.nextInt(nodes);
			final double[] p;
			if (previous != null && random.nextInt(5) == 0) {
				p = previous;
			} else {
				final double side = random.nextBoolean() ? 1 : -1;
				p = new double[] { centers[k][0] + (random.nextDouble() - 0.5) * sizes[k][0] * 0.8,
						centers[k][1] + side * sizes[k][1] / 2.0 + side * random.nextDouble() * 3 };
			}
			previous = p;
			obj.sz.x = 0;
			obj.sz.y = 0;
			obj.pos.x = p[0];
			obj.pos.y = p[1];
			xl.sz.x = 5 + random.nextInt(90);
			xl.sz.y = random.nextInt(4) == 0 ? 5 + random.nextInt(90) : 15;
			xl.set = 0;
			obj.lbl = lbls.plus_(l);
			l++;
		}
		final ST_label_params_t params = new ST_label_params_t();
		params.force = random.nextInt(6) != 0;
		params.bb.LL.x = Integer.MAX_VALUE;
		params.bb.LL.y = Integer.MAX_VALUE;
		params.bb.UR.x = -Integer.MAX_VALUE;
		params.bb.UR.y = -Integer.MAX_VALUE;
		for (int i = 0; i < n_objs; i++) {
			final ST_object_t obj = objs.get__(i);
			params.bb.LL.x = Math.min(params.bb.LL.x, obj.pos.x);
			params.bb.LL.y = Math.min(params.bb.LL.y, obj.pos.y);
			params.bb.UR.x = Math.max(params.bb.UR.x, obj.pos.x + obj.sz.x);
			params.bb.UR.y = Math.max(params.bb.UR.y, obj.pos.y + obj.sz.y);
		}
		out.println("place " + n_objs + " " + labels + " force " + (params.force ? 1 : 0) + " bb " + hex(params.bb.LL.x)
				+ " " + hex(params.bb.LL.y) + " " + hex(params.bb.UR.x) + " " + hex(params.bb.UR.y));
		for (int i = 0; i < n_objs; i++) {
			final ST_object_t obj = objs.get__(i);
			out.println("obj " + hex(obj.pos.x) + " " + hex(obj.pos.y) + " " + hex(obj.sz.x) + " " + hex(obj.sz.y) + " "
					+ (obj.lbl == null ? "-" : String.valueOf(obj.lbl.minus_(lbls))));
		}
		for (int i = 0; i < labels; i++) {
			final ST_xlabel_t xl = lbls.get__(i);
			out.println("lbl " + hex(xl.sz.x) + " " + hex(xl.sz.y));
		}
		final int r = xlabels__c.placeLabels(Globals.open(), objs, n_objs, lbls, labels, params);
		out.println("result " + r);
		for (int i = 0; i < labels; i++) {
			final ST_xlabel_t xl = lbls.get__(i);
			out.println("placed " + hex(xl.pos.x) + " " + hex(xl.pos.y) + " " + xl.set);
		}
	}
}
